### ISSUE TITLE
Add NgModules

### ISSUE THREAD

**Issue by tb** [Promact/md2#11]
@dharmeshpipariya first of all thank you for awesome work!

Adding NgModules would be greater, see https://github.com/angular/material2/pull/950

**Comment by dharmeshpipariya-zz** [comment]
@tb we are working on it, we will update soon.

**Comment by dharmeshpipariya-zz** [comment]
@tb we have added NgModules on all components and published on npm you can refer our latest code on [https://github.com/Promact/material2/tree/promact](https://github.com/Promact/material2/tree/promact) and use from npm on [https://www.npmjs.com/package/md2](https://www.npmjs.com/package/md2)

**Comment by tb** [comment]
@dharmeshpipariya I find it confusing that md2 package is published from https://github.com/Promact/material2/tree/promact

Why you are not using https://github.com/Promact/md2/tree/master?

I would like to contribute to this project, i.e. help migrate to rc.6 or add some component tests.
