### ISSUE TITLE
MD2-select Object definition

### ISSUE THREAD

**Issue by AngularTx** [Promact/md2#111]
When using the md2-select feature, is it very necessary that the object should be in format  like "{ name: 'Amsterdam', value: '1', disabled: false }," to be used in the select drop down . 

Or this package can be make use of other object types aswell? 
Eg : { employeename: 'abc" , employeeid: 123 , employeegroup : 1234} ;

**Comment by dharmeshpipariya-zz** [comment]
@AngularTx please refer [https://github.com/Promact/md2/blob/master/src/lib/select/README.md](https://github.com/Promact/md2/blob/master/src/lib/select/README.md)
you can use any type of object.
