### ISSUE TITLE
Pagination Issue In Data Grid

### ISSUE THREAD

**Issue by ahirhasmukh** [Promact/md2#112]
Data-Grid's data doesn't bind on `<md2-pagination [rowsPerPageSet]="[5,10,15]"></md2-pagination>` and doesn't show as well on grid. some issue is replace parameters `md-rows` to `rowsPerPageSet`

**Comment by dharmeshpipariya-zz** [comment]
@smartHasmukh we have released md2@0.0.16 and fixed the issue in it, comment here is any issue
