### ISSUE TITLE
datepicker reactive form disable

### ISSUE THREAD

**Issue by mbeckenbach** [Promact/md2#114]
The datepicker ignores disabled state of a from control when using reactive forms:

this.form = new FormGroup({
      'dateStart': new FormControl({value: null, disabled: this.isInReadOnlyMode}),

when you add the disabled attribute in addition, it works:
<md2-datepicker
              type="date"
              format="DD.MM.YYYY"
              placeholder="Datum"
              formControlName="dateStart"
              [disabled]="isDisabled"
            ></md2-datepicker>

But then you get this angular warning:

 It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.
       
      Example: 
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });

**Comment by josephserrano15** [comment]
Hello,

I am having the same issue.

 ngModel cannot be used to register form controls with a parent formGroup directive. Try using↵ formGroup's partner directiv…

**Comment by dharmeshpipariya-zz** [comment]
@josephserrano15 which version you have used of md2?

**Comment by josephserrano15** [comment]
I am using  "md2": "0.0.19".

**Comment by dharmeshpipariya-zz** [comment]
duplicate #181
