### ISSUE TITLE
Datepicker breaks when setting time value in HH:mm format

### ISSUE THREAD

**Issue by mtinnes** [Promact/md2#117]
Binding a time value in HH:mm format to the Datepicker value causes the following error:

`./Md2Datepicker class Md2Datepicker - inline template:0:1305 caused by: Invalid argument 'Invalid Date' for pipe 'DatePipe'
`
Apparently the DatePipe is still being evaluated even when 'time' is selected as the picker type.

For example, the following does not work:
```
<md2-datepicker
type="time"
format="HH:mm"
value="03:44">
```

**Comment by dharmeshpipariya-zz** [comment]
@mtinnes Bind date object instead of static string, we will provide support later.
