### ISSUE TITLE
No provider for ColorpickerService

### ISSUE THREAD

**Issue by djanesch** [Promact/md2#119]
hy all!

i use md2 0.0.16 and want to use also colorpicker.
but when i include the colorpicker i get the following error: No provider for ColorpickerService
i have also tried to add the service with providers in the component but this leads to an other error:
Can't resolve all parameters for Md2Colorpicker: ([object Object], [object Object], [object Object], [object Object], ?, [object Object])

could you please give me a hint whats wrong?

following the relevant files:
html:
`<md2-colorpicker [(ngModel)]="_color" [disabled]="true" id="color_{{ thema.id }}"></md2-colorpicker>`

component without providers:
`import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'oase-dummy',
  templateUrl: './dummy.component.html',
  styleUrls: ['./dummy.component.css']
})
export class DummyComponent implements OnInit {
  private _color: string = '#654321';
  constructor() { }
  ngOnInit() {
  }
}`

component with providers:
`import { ColorpickerService } from 'md2/colorpicker/calculateColor';
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'oase-dummy',
  templateUrl: './dummy.component.html',
  styleUrls: ['./dummy.component.css'],
  providers: [ColorpickerService]
})
export class DummyComponent implements OnInit {
  private _color: string = '#654321';
  constructor() { }
  ngOnInit() {
  }
}`

best regards daniel

**Comment by dharmeshpipariya-zz** [comment]
@djanesch we have fixed this issue in release @0.0.17
