### ISSUE TITLE
Multiselect does not close on IE11

### ISSUE THREAD

**Issue by tb** [Promact/md2#12]
Tested on http://code.promactinfo.com/md2/multiselect

**Comment by dharmeshpipariya-zz** [comment]
@tb now we are just targeting latest Chrome browser only, we will provide support for all browser once Angular2 stable. you can also send PR on promact branch of [https://github.com/Promact/material2](https://github.com/Promact/material2)

**Comment by dharmeshpipariya-zz** [comment]
This issue has been updated.
