### ISSUE TITLE
datepicker doesn't work on IPad 2

### ISSUE THREAD

**Issue by matte00** [Promact/md2#120]
Hi, mate and thank you so much for this great library! 
I  opened md2 demo with my IPad 2 but when i click on md2-datepicker demo it's don't work. (Intl not supported). Touch in hour / minute selection doesn't work.

I don't know if you already know this, is there a fix?

EDIT: I tested it with Chrome 56.0.2924.79 on IOS 9.3.5

EDIT: The error in Chrome's console:
```
undefined:0
Error: Error in ./Md2Datepicker class Md2Datepicker - inline template:0:1846 caused by: Can't find variable: Intl
```

**Comment by matte00** [comment]
Hi mate, i resolved partially the issue with Intl polyfills. **But touch issues on IPAD 2 remain.**

`> npm install intl` [https://www.npmjs.com/package/intl](url)

`
if (!global.Intl) {  
    require.ensure([
        'intl',
        'intl/locale-data/jsonp/en.js'
    ], function (require) {
        require('intl');
        require('intl/locale-data/jsonp/en.js');
    });
}`

**Comment by dharmeshpipariya-zz** [comment]
@matte00 we have fixed this issue.
