### ISSUE TITLE
i18n directive not working

### ISSUE THREAD

**Issue by victorpigmeo** [Promact/md2#122]
I created a directive to translate the datepicker to pt-BR, in version 0.0.14 it was working, but I updated to 0.0.16 and it stops working, the datepicker has something that I can use to translate it? If not, how can I change the values in the _locale property to show it translated?

**Comment by dharmeshpipariya-zz** [comment]
@victorblq we have implemented local service of date picker you can use it.

**Comment by Toub** [comment]
@dharmeshpipariya could you provide information or documentation about how to add languages using this local service.

https://github.com/Promact/md2/blob/master/src/lib/datepicker/date-locale.ts

**Comment by dharmeshpipariya-zz** [comment]
@Toub you can inject `DateLocale` service in your component and then re-assign its properties those you want to need.

**Comment by Toub** [comment]
Thanks. An example would be nice, as well as a way to contribute to translations.

**Comment by abiranjan** [comment]
Find the implementation below incase if it will be helpful for someone.

1) Import the DateLocale service from md2
2) Re assign the values to the type you want to be changed. (ex.months here)

import { DateLocale } from 'md2';
export class myComponent  {

  private Month = {
  'long': [
    'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
    'October', 'November', 'December'
  ],
  'short': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  'narrow': ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']
  } ;

  constructor(private myDate : DateLocale) {    
    this.myDate.months = this.Month;
}

}
