### ISSUE TITLE
<template> is deprecated in Angular 4, use ng-template instead

### ISSUE THREAD

**Issue by hccampos** [Promact/md2#125]
When using md2 with Angular 4 RC, we get several warnings stating that `<template>` has been deprecated and that `<ng-template>` should be used instead:

```
The <template> element is deprecated. Use <ng-template> instead ("[style.background-color]="color"></div></div><label class="color-text">{{color}}</label></div></div>[WARNING ->]<template portal><div class="md2-colorpicker-panel"><div class="md2-colorpicker-content"><div class="")
```

What are your plans regarding upgrade to Angular 4? This is something that should be addressed but hopefully in some way that doesn't break things for users that are in Angular 2.x.x.

**Comment by dharmeshpipariya-zz** [comment]
@hccampos Now MD2 is stable and depend on the Angular@2.*.*, we will update later

**Comment by morocarlo** [comment]
@dharmeshpipariya can you update it to angular4?

**Comment by hccampos** [comment]
@morocarlo https://github.com/Promact/md2/pull/142

**Comment by dharmeshpipariya-zz** [comment]
@morocarlo we have updated it with angular 4, will release it soon

**Comment by dharmeshpipariya-zz** [comment]
We have updated angular4 with release of md2@0.0.18.
