### ISSUE TITLE
Tooltip alignment issue when set long string in tooltip

### ISSUE THREAD

**Issue by ahirhasmukh** [Promact/md2#126]
Hello,

Please check attachment. Tooltip align disturb when I have set long string like 20 or to more characters.

![tooltip_issue](https://cloud.githubusercontent.com/assets/8941195/24071407/f356025a-0bf6-11e7-93bf-11ec1973979b.png)

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya Above issue doesn't resolved in latest 0.0.17

**Comment by dharmeshpipariya-zz** [comment]
@smartHasmukh it's working fine you can check our [Demo](http://code.promactinfo.com/md2/#/tooltip), or provide more details about the issue, so I will help you.

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya Please check screenshot. It is issue. When button position right than issue occurred 

![tooltip_issue](https://cloud.githubusercontent.com/assets/8941195/24132606/e48899ae-0e1c-11e7-80e3-378085bd4b39.png)

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya  Did fixed?

**Comment by dharmeshpipariya-zz** [comment]
@smartHasmukh yes.
