### ISSUE TITLE
AoT Build Errors w/ 0.0.17

### ISSUE THREAD

**Issue by rosslavery** [Promact/md2#128]
md2 Version: md2@0.0.17
ng version: 2.4.8

Following errors when building w/ AoT:
```
ERROR in [at-loader] compiled\node_modules\md2\colorpicker\colorpicker.ngfactory.ts:249:41
    TS2339: Property 'inputFocused' does not exist on type 'Md2Colorpicker'.

ERROR in [at-loader] compiled\node_modules\md2\colorpicker\colorpicker.ngfactory.ts:1301:41
    TS2341: Property 'isInputValidColor' is private and only accessible within class 'Md2Colorpicker'.

ERROR in [at-loader] compiled\node_modules\md2\colorpicker\colorpicker.ngfactory.ts:1340:9
    TS2322: Type 'QueryList<any>' is not assignable to type 'Portal<any>'.
  Property '_attachedHost' is missing in type 'QueryList<any>'.
```

3rd one seems the same as #118 .

**Comment by mbeckenbach** [comment]
@rosslavery 
This one also happens when building with angular 4.0 and aot

ERROR in [at-loader] compiled\node_modules\md2\colorpicker\colorpicker.ngfactory.ts:1301:41
    TS2341: Property 'isInputValidColor' is private and only accessible within class 'Md2Colorpicker'.

**Comment by hccampos** [comment]
This is probably due to private variables being disallowed in templates as of Angular 4.0.0. In the previous version, the errors were being omitted. We are also experiencing this on our side.

**Comment by hccampos** [comment]
Just made a PR that should hopefully get the ball going https://github.com/Promact/md2/pull/142/files

**Comment by djanesch** [comment]
I get same errors three errors with md2 Version 0.0.17 and ng version 2.4.10

**Comment by hccampos** [comment]
If anyone wants to give a try to our custom build, here it is: https://github.com/Pix4D/md2-dist

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.18,
comment here if you have an issue

**Comment by n4uoase** [comment]
Now as I updated to md2@0.0.18 when I run the compiler for aot i got following error:
`Error encountered resolving symbol values statically. Could not resolve @angular/animations relative to client-app/node_modules/md2/accordion/accordiontab.d.ts., resolving symbol Md2AccordionTab in client-app/node_modules/md2/accordion/accordiontab.d.ts, resolving symbol Md2AccordionTab in client-app/node_modules/md2/accordion/accordiontab.d.ts, resolving symbol Md2AccordionTab in client-app/node_modules/md2/accordion/accordiontab.d.ts`

**Comment by dharmeshpipariya-zz** [comment]
you have to install animation package of angular as `npm install @angular/animations --save`

**Comment by n4uoase** [comment]
But @angular/animations is version 4.0. We are working with Angular 2.4.10.
Any other solution to solve this?

**Comment by dahaupt** [comment]
@n4uoase You should consider upgrading to Angular 4. It's pretty easy and I had no problems in my application doing that.
