### ISSUE TITLE
Question: How to change datepicker header background color?

### ISSUE THREAD

**Issue by suhotskiy** [Promact/md2#130]

**Comment by dharmeshpipariya-zz** [comment]
@suhotskiy  you have to overwrite styles of it, you can also use our [SASS](https://github.com/Promact/md2/blob/master/src/lib/datepicker/datepicker.scss) to change the color and theme too.

**Comment by shalugin** [comment]
@dharmeshpipariya why me? Maybe @suhotskiy? :)

**Comment by dharmeshpipariya-zz** [comment]
@shalugin it was by mistake. I have updated it.
