### ISSUE TITLE
Working with master - guidance needed

### ISSUE THREAD

**Issue by HopScotch47** [Promact/md2#133]
Hey there, thanks for your effort - these are really nice components.

When I want to use the master branch in my project I follow the readme to do this:
`npm install --save https://github.com/Promact/md2.git`

When I then try to import the module, it is not there since obviously the module has not built. I then try to do this instead:

`import { Md2Module } from 'md2/src/lib/module';`

which results in several errors regarding missing css files, since in the source only scss files exist.
Is there any guidance on how to get around this? I can get around it by manually compiling the scss files, but in my CI which operates on a clean checkout that wouldn't work.

Thanks for your help

**Comment by dharmeshpipariya-zz** [comment]
@HopScotch47 you have to install md2 package from npm instead of git repo as -> `npm install --save md2` and refer Our [guidelines](https://github.com/Promact/md2/blob/master/README.md)

**Comment by HopScotch47** [comment]
Well, of course that works. The problem comes when I need the master branch
because a fix is not in a release yet.

So... How can I make it work with the master branch... Or... When will the
next release drop?

**Comment by dharmeshpipariya-zz** [comment]
@HopScotch47 you can use the master branch for development for that you need to follow steps as:
1. clone the git repo.
2. run `npm install`
3. run `gulp :build:components:release`
4. run `gulp :build:release:clean-spec`
5. goto dist/md2 folder path and use it

**Comment by ghost** [comment]
Thanks @dharmeshpipariya

**Comment by ajinkyaskulkarni** [comment]
Hello Dharmesh ,

First of thanks for such a nice component. I have a question maybe a naive one  :) , I would like override some of CSS attributes in my custom component and somwhow i am not able to override it. Can you give me some hint.
