### ISSUE TITLE
Datepicker clear should be optional

### ISSUE THREAD

**Issue by mbeckenbach** [Promact/md2#136]
see subject

**Comment by dharmeshpipariya-zz** [comment]
@mbeckenbach set `required` property to hide clear option

**Comment by mbeckenbach** [comment]
@dharmeshpipariya 
In my use case the field is not required but the user should not be able to reset the date after it has been set one. The user may change the date but must never be able to clear it.

**Comment by dharmeshpipariya-zz** [comment]
@mbeckenbach we plan for this feature and let you know.

**Comment by mbeckenbach** [comment]
@dharmeshpipariya 
Thank you. For the moment i've simply set the css for the clear icon to display:none
