### ISSUE TITLE
Implementation of translator for day, month and year

### ISSUE THREAD

**Issue by hiagodotme** [Promact/md2#139]
Hello, how do I create a property for me to pass an object informing a nomenclature of the days month and year?

For my language is not English.

Thank you

**Comment by dharmeshpipariya-zz** [comment]
@hiagodotme you can use locale service of date picker component and update content of days and months  but the year is now coming in the English language

**Comment by hiagodotme** [comment]
I know but I would like to know the possibility of informing the name of the months, days, years and weeks. This without changing directly in the code of the component

**Comment by hiagodotme** [comment]
Sorry if I'm not being clear I'm using google translate
