### ISSUE TITLE
Datepicker calendar z-order

### ISSUE THREAD

**Issue by HopScotch47** [Promact/md2#145]
Infrequently I have the issue that if the datepicker panel is opened on a modal dialog (I am using angular/material2), it is rendered below the dialog window. 
Sometimes a browser refresh helps, sometimes it doesn't.

I have not yet figured out what the cause for that is. 
Any thoughts?

Thanks

**Comment by dharmeshpipariya-zz** [comment]
this issue has been fixed in latest version.
