### ISSUE TITLE
Input type in md2-datepicker doen't works on mobile

### ISSUE THREAD

**Issue by matte00** [Promact/md2#146]
Hi mate,

with last change in md2-datepicker when input box is focused in mobile browser the keyboard  appears and datapicker is immediately closed

**Comment by acovrig** [comment]
I have another problem I'm guessing is related - When I tap an input on my android, it bounces focus to the date input instead for some reason (https://gist.github.com/acovrig/72cdbc2a8c30c5d40824d08ff02548a4). If I tap the cost field, it focuses it, then ~500ms later focuses the date input.

I attached a gif screencap of it, it also shows the issue @matte00 mentions:
![2017-05-13-07-31-43](https://cloud.githubusercontent.com/assets/5814627/26025224/bc92abf2-37b0-11e7-964a-4433301d53d5.gif)

**Comment by dharmeshpipariya-zz** [comment]
We have improved behavior of datepicker.
