### ISSUE TITLE
Allow setting of type attribute of input on md2-chips

### ISSUE THREAD

**Issue by DanRibbens** [Promact/md2#147]
The current behavior for md2-chips is that the <input> is made with type="string". It would be nice to have type be an optional property that can be set to some of the other html5 input types. 
One use case is when building for mobile devices, it is nice to have a type to get the appropriate keyboard.

**Comment by krupa310** [comment]
@DanRibbens We have set "allowedPattern" attribute to set the specific type of chip.If You define it then it allows only that particular type of chip.For More information refer the [document](https://github.com/Promact/md2/blob/master/src/lib/chips/README.md)

**Comment by DanRibbens** [comment]
I am already using the allowedPattern to match a regex which helps, but it doesn't get the right keyboard on mobile devices.  If I need this feature, could I implement and make a PR?

**Comment by dharmeshpipariya-zz** [comment]
@DanRibbens yes, you can contribute.

**Comment by DanRibbens** [comment]
https://github.com/Promact/md2/pull/180
Merged
