### ISSUE TITLE
Datepicker should have a customizable icon

### ISSUE THREAD

**Issue by Robin-Hoodie** [Promact/md2#148]
Right now there seems to be no option to change the default calendar icon to an icon of your own liking (e.g. a birthday cake for a user's birthday field)

**Comment by dharmeshpipariya-zz** [comment]
@Robin-Hoodie we have implemented `md2DatepickerToggle` directive you can use it and customize styles to add your customizable icon, refer [API DOC](https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md)
