### ISSUE TITLE
md2 throws error without BrowserAnimationsModule in angular 4

### ISSUE THREAD

**Issue by csis0247** [Promact/md2#150]
Upon upgrading md2 from 0.0.13-1 to 0.0.18 to support angular 4.0.0 using @angular/cli, md2-datepicker no longer opens with error `Error: Found the synthetic listener @fadeInContent.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`. Tested on latest Chrome and Firefox.

Solution (3 steps):
`npm install @angular/animations --save`
`import {BrowserAnimationsModule} from '@angular/platform-browser/animations'` inside app.module.ts
And then add BrowserAnimationsModule to NgModule as follows
`@NgModule({
     imports: [
       BrowserAnimationsModule
     ]
})`

This should be included in the setup guide as the imports do not occur by default, or preferably supported within the md2 library.

**Comment by dharmeshpipariya-zz** [comment]
@csis0247 Yes, you have to install animation and platform browser packages of angular as `npm install @angular/animations --save` and `npm install @angular/platform-browser --save`

**Comment by gokhandeveloper** [comment]
I am having the same issue with this as well. I included the 

`import { BrowserModule } from '@angular/platform-browser';
`
What is the animations folder under platform-browser for?

Can the the md2-datepicker show time if installed standalone?

**Comment by dharmeshpipariya-zz** [comment]
@gokhandilek import `import {BrowserAnimationsModule} from '@angular/platform-browser/animations';` and import `BrowserAnimationsModule` in your app module
