### ISSUE TITLE
Datepicker - return result as formatted string

### ISSUE THREAD

**Issue by vfedoriv** [Promact/md2#154]
Is it possible to get datepicker result as formatted string.
As example, now I set format [format]= 'yyyy/MM/dd' and get result as Date: 2017-04-03T20:52:00.000Z
Need just string '2017/04/03'.

**Comment by dharmeshpipariya-zz** [comment]
@vfedoriv we are returning object of Date, you can use date pipe and format it easily, refer [https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html](https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html)

**Comment by vfedoriv** [comment]
It's not for display, i mean output formatting for backend.
After getting object from form I use something like
`
visit.date = new Date(visit.date).toISOString().substring(0, 10).replace(/-/g, '/');
`
and set date field as 'yyyy/mm/dd' string before send object to backend.
( where visit.date - field, binded to datepicker ).

**Comment by dharmeshpipariya-zz** [comment]
@vfedoriv you have to convert date in specific format as:
`formatDate(date) {
  return date.getFullYear() + '-' + (date.getMonth() + 1) + '-' +date.getDate()
}
let date = new Date()
console.log(this.formatDate(date));
`
