### ISSUE TITLE
is there a way to style the element color ?

### ISSUE THREAD

**Issue by nobitahuang** [Promact/md2#155]
hi, i want to style the md2 dialog header , is that possible ?

**Comment by dharmeshpipariya-zz** [comment]
@chendzng yes, you can override its style locally

**Comment by nobitahuang** [comment]
can i have the example how to change the background color of the md2-dialog header ? thanks

**Comment by nobitahuang** [comment]
@dharmeshpipariya

**Comment by dharmeshpipariya-zz** [comment]
@chendzng  you can use our [scss](https://github.com/Promact/md2/blob/master/src/lib/dialog/dialog.scss) for it
