### ISSUE TITLE
datepicker Issue after update

### ISSUE THREAD

**Issue by nikeshjain** [Promact/md2#159]
---------------------First Issue-----------------------------------
When i enter  invalid date and then i enter valid date  it's  show error
Cannot read property 'getDate' of null 
At line  DateUtil.isSameDay (md2.umd.js:8598)
------------------------Second issue----------------------------
When i enter  invalid date it's mix up value and place holder 
please check in attachment 
please resolve this issues as soon as possible 
![datepicker issue](https://cloud.githubusercontent.com/assets/23694120/24704072/b3611ef6-1a23-11e7-8d61-840481e32c05.png)

**Comment by kambbado** [comment]
The issue seems to be in the "isSameDay" function in date-util.js file, the parameter "d1" is null on the time the function is called.

Changing  the "isSameDay" in the .js file fix it, but this may not be the appropriate fix.

` DateUtil.prototype.isSameDay = function (d1, d2) {
		if (d1 && d2) {
                           return d1.getDate() == d2.getDate() && this.isSameMonthAndYear(d1, d2);
		} else {
			return false;
		}
    };`

**Comment by timodufour** [comment]
This issue seems to be fixed in the DateUtil code, but isn't released yet. Any idea when a new release will become available?
