### ISSUE TITLE
Can't import Md2Module into project created and built with angular-cli beta 15

### ISSUE THREAD

**Issue by adrian-heath** [Promact/md2#16]
When trying to import the library into a project built using beta 15 of the angular cli and webpack I follow the same steps as other libraries and add 

import { Md2Module } from 'md2/all';

and add Md2Module.forRoot() to the NgModule imports

in app.module.ts

It builds fine but on running it gives the error 

Uncaught Error: Cannot find module "."

This happens even with or without .forRoot and also for importing individual modules such as Md2DatePicker

Can you update the documentation with the correct configuration to get everything running with the angular cli.

Thanks

**Comment by dharmeshpipariya-zz** [comment]
@adrian-heath please refer our demo code for MD2 [demo code ](https://github.com/dharmeshpipariya/material2-demo) also use latest version of md2 is 0.0.0-alpha.7

**Comment by adrian-heath** [comment]
@dharmeshpipariya  This still doesn't work with the latest angular-cli boilerplate project which no longer uses systemjs.  You can recreate this easily by following these steps.

**npm Install angular-cli beta 15**
**ng new md2-test**
**cd md2-test**
**ng serve**

browse to localhost:4200 and should see **App works!**

**npm install --save md2**

open app.module.ts and add
     **import { Md2Module } from 'md2/all';**
and add 
     **Md2Module.forRoot()** to the imports

run **ng serve** again

this time the browser sticks on laoding and the console shows the error

**Uncaught Error: Cannot find module "."**

**Comment by elizabetdev** [comment]
@dharmeshpipariya I have the same problem:

```
Uncaught Error: Cannot find module "."
webpackMissingModule    @ all.js:12
```

**Comment by sitexw** [comment]
I have exactly the same problem (but I do not use Angular CLI)
![image](https://cloud.githubusercontent.com/assets/2950561/19029492/0fd64f76-8947-11e6-98a9-7f65a6e237f5.png)

**Comment by Mufasa** [comment]
I also get exactly the same problem - I am using Angular CLI **v1.0.0-beta.16** and md2 **v0.0.2**

My **app.module.ts** file contains:

```
...
import { Md2Module } from 'md2/all';
...
@NgModule({
  declarations: [...],
  imports: [
    ...,
    Md2Module.forRoot()
  ],
  ...
```

This error seems to occur at the point where **Md2Module.forRoot()** is called, giving the stacktrace shown by @sitexw.

I haven't even got any code that uses any of the **Md2** directives in any of my html files yet.

2016/10/07: Just tried again with **v0.0.3** of md2 - same error :(
2016/10/11: Just tried again with **v0.0.4** of md2 - same error :(
2016/10/20: Just tried again with **v0.0.6** of md2 - this time get a new error:

```
metadata_resolver.js:700
Uncaught Error: moduleId should be a string in "Md2TooltipComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
```

**Comment by sitexw** [comment]
In fact, the error occurs when compiling webpack:
![image](https://cloud.githubusercontent.com/assets/2950561/19153944/c4754de0-8bd8-11e6-9d90-f5d7b01aaf0e.png)

**Comment by gorkamolero** [comment]
Also using this with a **Webpack** based setup and having the same error. **Help needed!**

**Comment by rafaelss95** [comment]
I got the same using Angular WebPack.

**Comment by gorkamolero** [comment]
Any word on this?

**Comment by dharmeshpipariya-zz** [comment]
We have fixed this issue with release md2@0.0.6,
comment here if you have an issue

**Comment by aroop** [comment]
Issue if fixed for me with the latest version of md2. Thanks.

**Comment by gorkamolero** [comment]
Works like magic. Thank you

**Comment by Mufasa** [comment]
It hasn't been fixed for me.
I am using Angular CLI **v1.0.0-beta.17** and md2 **v0.0.6**

My **app.module.ts** file contains:

```
...
import { Md2Module } from 'md2';
...
@NgModule({
  declarations: [...],
  imports: [
    ...,
    Md2Module.forRoot()
  ],
  ...
```

I haven't even got any code that uses any of the **Md2** directives in any of my html files yet.

With this latest release of **md2** I get a new error:
![screen shot 2016-10-22 at 12 11 18](https://cloud.githubusercontent.com/assets/543618/19618948/d0cee892-9850-11e6-9e48-ed79caf43583.png)

**Comment by mkkr** [comment]
I have the same config as you Mufasa, and I had the same issue.
I fixed it by commenting this line in the "node_modules/md2/tooltip/tooltip.component.ts" : 
`moduleId: module.id,`
So now I have : 
`// moduleId: module.id,`

**Comment by Mufasa** [comment]
**mkkr** - thanks for the tip - your suggestion gave me an insight that I tried - I changed the line in the `node_modules/md2/tooltip/tooltip.component.ts` from:

```
moduleId: module.id,
```

to:

```
moduleId: String(module.id),
```

Now I don't get the error :)

**Comment by dharmeshpipariya-zz** [comment]
We have fixed this issue with release md2@0.0.7,
comment here if you have an issue

**Comment by nlubin-lv** [comment]
I am having the same issue in the latest release

![screen shot 2017-01-23 at 4 44 01 pm](https://cloud.githubusercontent.com/assets/23195416/22224032/2d6ffc2a-e18b-11e6-96e1-82bcdea94105.png)

@dharmeshpipariya

**Comment by sunillokhande** [comment]
https://github.com/dharmeshpipariya/material2-demo/issues/1
