### ISSUE TITLE
Aot build errors

### ISSUE THREAD

**Issue by sandor-huszar** [Promact/md2#160]
datepicker/month-view.ngfactory.ts:113:42
Property 'date' does not exist on type 'Date'.
maybe problem in file ../datepicker/month-view.html in this line [activeCell]="activeDate.date - 1"
and ../datepicker/year-view.html in this line [activeCell]="activeDate.month" too.

**Comment by dahaupt** [comment]
@sandor-huszar Which version of md2 do you use? We need more information to reproduce your issue.

**Comment by sandor-huszar** [comment]
last version 0.0.18

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the aot issue in latest release as md2@0.0.19 with angular4
