### ISSUE TITLE
Datepicker result in IE11

### ISSUE THREAD

**Issue by IamArtur** [Promact/md2#162]
Hello, 
the Datepicker result seems to be not correct in IE11 with type datetime and formats with Hours, Minutes and Seconds.

**Comment by jurri-cz** [comment]
It's probably a more generic bug in Angular (or Intl):
https://github.com/angular/angular/issues/9524
https://github.com/angular/angular/issues/10147

For the time being, including _ie.intl.shim.js_ (drop it to assets and include in your polyfills.ts) from this bugfix helped me:
https://github.com/Deutsche-Boerse-Risk/DAVe-UI/issues/7
