### ISSUE TITLE
time bug

### ISSUE THREAD

**Issue by 121595113** [Promact/md2#164]
当我选择time模式的时候，输入框在失去焦点的时候总是自动加5分钟

**Comment by dharmeshpipariya-zz** [comment]
@121595113 please provide more details.

**Comment by 121595113** [comment]
Look at the screenshots
<img width="532" alt="2017-04-19 23 15 41" src="https://cloud.githubusercontent.com/assets/9419773/25187693/64b5980c-2556-11e7-8b41-43b90c185a5b.png">
