### ISSUE TITLE
Datepicker feature request: Ability to specify time intervals

### ISSUE THREAD

**Issue by zdhz** [Promact/md2#165]
I would personally like the ability to specify the minute intervals for the datetimepicker, as there are a lot of use-cases where we only need the time rounded to the nearest 5 minute interval.

Most events (i.e. meetings, classes, conferences) will start at a time rounded to the nearest 5. In this case, we do not care for minutes 1-4 & 6-9.

Maybe something along the lines of:  
```
<md2-datepicker
     timeInterval="5">
</md2-datepicker>
```

where timeInterval is either minutely or 5-minutely.

**Comment by imichelakos** [comment]
+1
