### ISSUE TITLE
Is that possible to select Month also?

### ISSUE THREAD

**Issue by tshaik49** [Promact/md2#168]
Currently we can select the year, is it possible we can select month also instead of clicking to go to a specific month?

**Comment by imichelakos** [comment]
+1

**Comment by dharmeshpipariya-zz** [comment]
@tshaik49 , @imichelakos we have added functionality for month picker in datepicker, you can set type="month" and use it. refer [API Docs](https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md)
