### ISSUE TITLE
Upgrade to Angular 4

### ISSUE THREAD

**Issue by fredpolicarpo** [Promact/md2#169]
I need to upgrade my application to Angular 4, but I'm having the following problem:

```
npm WARN md2@0.0.17-2 requires a peer of @angular/core@^2.3.0 but none was installed.
npm WARN md2@0.0.17-2 requires a peer of @angular/common@^2.3.0 but none was installed.
npm WARN md2@0.0.17-2 requires a peer of @angular/http@^2.3.0 but none was installed.

```

**Comment by dharmeshpipariya-zz** [comment]
@fredpolicarpo use md2@0.0.18 version, it is compatible with angular@4

**Comment by deepakzoto** [comment]
Got this error while using it with webpack.

md2.umd.js:9 Uncaught TypeError: Cannot read property 'Observable' of undefined
    at c (md2.umd.js:9)
    at md2.umd.js:10

**Comment by dharmeshpipariya-zz** [comment]
@deepakzoto you have to install `rxjs` in your project using `npm install --save rxjs`

**Comment by theanadimukt** [comment]
i have installed `rxjs@5.2.0` and also `md2@0.0.18` in angular 4 CLI although getting `Observable` error.

included `md.umd.js` in **.angular-cli.json**

```
"scripts": [
        "../../../node_modules/md2/bundles/md2.umd.js"
      ],
```

**app.module.ts**

```
import { Md2Module }  from 'md2';
@NgModule({
  imports: [
    ...,
    Md2Module.forRoot(),
  ],
  ...
})
```
