### ISSUE TITLE
Reset value

### ISSUE THREAD

**Issue by iLavs** [Promact/md2#170]
How I can reset a value of datepicker?

**Comment by dharmeshpipariya-zz** [comment]
@iLavs you have to add control on ngModel of date picker as
`<md2-datepicker [(ngModel)]="date" #dateControl="ngModel"></md2-datepicker>`
and use `dateControl` control to reset it as 
`<button type="button" (click)="dateControl.reset()">RESET</button>`
or you can reset it through programatically too.
