### ISSUE TITLE
Datepicker Timezone

### ISSUE THREAD

**Issue by warmans** [Promact/md2#174]
I don't know if I'm just missing something but I think currently the datepicker will always generate a date in the browser timezone. This causes a problem for me because I would like to use UTC dates instead. I thought I could just fix the date object on `(change)` or something but this appears to break the selected display date logic and the selected date will move to the next day. It would be awesome if you could tell the date picker to generate dates in UTC instead of the default timezone or if you could suggest a workaround.

Many thanks.

**Comment by nichovski** [comment]
+1
