### ISSUE TITLE
datepicker decrements date on blur

### ISSUE THREAD

**Issue by letthewookieewin** [Promact/md2#177]

**Comment by Hyperonic** [comment]
I'm also getting this bug. using v0.0.19

**Comment by letthewookieewin** [comment]
Hey @hyperonic, what does your format look like? I changed mine from MM/dd/yy to MM/dd/yyyy and it worked after that.

**Comment by dharmeshpipariya-zz** [comment]
@Hyperonic please refer [https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md](https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md) docs of datepicker

**Comment by Hyperonic** [comment]
@letthewookieewin @dharmeshpipariya.  I'm using format y. After selecting year, If I click anywhere outside the field, the year moves back 1 year

**Comment by dharmeshpipariya-zz** [comment]
@Hyperonic could you provide more details or plunkr demo?

**Comment by Hyperonic** [comment]
@dharmeshpipariya [http://plnkr.co/edit/GSdXakoZigRGrrBrWb7N](http://plnkr.co/edit/GSdXakoZigRGrrBrWb7N)

**Comment by laurentperroteau** [comment]
I open a similar issue few days ago #186

**Comment by laurentperroteau** [comment]
I fix date parsing bug by overriding ["parseDate" method in DateUtil class](https://github.com/Promact/md2/blob/a84b45c98fa12c3e93e2f7d22b6a9ebf3168bcaa/src/lib/datepicker/date-util.ts#L107) and changing regex that match keyword format from `/[dmhkyhs]/i` to `/[dmMHys]/` (avoid insensitive case and list only letter listing in [the doc](https://github.com/Promact/md2/tree/18f27c19e5375a31028c070b90dc92ccaf507438/src/lib/datepicker#date-format).

@dharmeshpipariya, I can create a pull-request if it's looking good for you ?

**Comment by dharmeshpipariya-zz** [comment]
@laurentperroteau thanks, yes you can create PR
