### ISSUE TITLE
Tags not working as expected with some options

### ISSUE THREAD

**Issue by didacrios** [Promact/md2#179]
This is reproduced in version "md2": "0.0.16"

Using this array 
```typescript
let item = { name: "test", label: "Label" };

let options = [
                    {id: 1, description: "A" },
                    {id: 2, description: "P1" },
                    {id: 3, description: "P2" },
                    {id: 4, description: "P3" },
                    {id: 5, description: "P4" },
];
```

An in the template using
```html
 <md2-tags [md2-tags]="options" md2-tag-text="description" [formControlName]="item.name" [placeholder]="item.label">
</md2-tags>
```

When typing P only some options appear:

![image](https://cloud.githubusercontent.com/assets/211009/25229206/b72f5e00-25cf-11e7-9516-5f2a3632468b.png)

**Comment by dharmeshpipariya-zz** [comment]
@didacrios you have to assign property for text and value using 'md2-tag-text' and 'md2-tag-value' property, please refer tags [documentation](https://github.com/Promact/md2/blob/master/src/lib/tags/README.md)

**Comment by didacrios** [comment]
Many thanks.

What if I want to use the whole object as the value? 

BTW, using the md2-tag-value still not solve the problem
```html
 <md2-tags [md2-tags]="options" md2-tag-text="description" md2-tag-value="id" [formControlName]="item.name" [placeholder]="item.label">
</md2-tags>``

**Comment by dharmeshpipariya-zz** [comment]
@didacrios if you want to use the whole object as the value, then don't set `md2-tag-value` property.

`<md2-tags [md2-tags]="options" md2-tag-text="description"[formControlName]="item.name" [placeholder]="item.label">
</md2-tags>`

**Comment by didacrios** [comment]
@dharmeshpipariya that was my first approach in my first message

**Comment by dharmeshpipariya-zz** [comment]
@didacrios could you provide please plunkr demo, this is Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info
