### ISSUE TITLE
Access to Autocomplete Input text

### ISSUE THREAD

**Issue by MarcusCalidus** [Promact/md2#18]
Hello,

is there a way to access the input text value of the auto complete control? If not, this would be very convenient to have. 

Cheers 
Marco

**Comment by dharmeshpipariya-zz** [comment]
No, there is no any way to access the input text value of Autocomplete. You need to select any item from a list of Autocomplete in order to have value in a bounded model.

**Comment by damsorian** [comment]
@dharmeshpipariya If we need to get the data from the backend asynchronous? how is possible to access to `change` event of the input text in order to find based on the user writes on the input?

**Comment by dharmeshpipariya-zz** [comment]
@damsorian you can use 'textChange' event to get text of input

**Comment by l2radamanthys** [comment]
`textChange` fail and lost the last character pressed.  

Typescript is javascript with sugar, to access a private atribute example `_inputValue` in any moment

       <md2-autocomplete #autocomplete></md2-autocomplete>       

      @ViewChild('autocomplete', undefined) autocomplete: any;

      console.log(this.autocomplete['_inputValue']) //work for me, to get the full value of text input
