### ISSUE TITLE
Error md2-datepicker when using form group

### ISSUE THREAD

**Issue by josephserrano15** [Promact/md2#181]
Doesn't support Form Group.

 Error: Cannot find control with unspecified name attribute
HTML:
`<form id="userform" [formGroup]="userform" (ngSubmit)="processUserForm()">
<md2-datepicker name="BirthDay"
                                    type="date"
                                    placeholder="Birth Date"
                                    container = "inline"
                                    [required]=true
                                    [formControl]="userform.BirthDay"
                                    ></md2-datepicker>
`
 I did try a few things, but nothing seems to work.

TS:
`this.userform = this.fb.group({
      BirthDay: ['', Validators.compose([Validators.required])],
    });
`

Thanks for you hard work!

**Comment by josephserrano15** [comment]
I am using  "md2": "0.0.19" by the way.

**Comment by ghost** [comment]
@josephserrano15  Try the code below, also I wrapped the inputs of the md2-datepicker in brackets and also wrapped the strings in ''

```
<form id="userform" [formGroup]="userform" (ngSubmit)="processUserForm()"> 
<md2-datepicker 
    #BirthDay <!-TRY ADDING THIS->
    id="BirthDay" <!-TRY ADDING THIS->
    name="BirthDay" 
    [type]="'date'" 
    [placeholder]="'Birth Date'" 
    [container] = "'inline'" 
    [required]="true" 
    [formControl]="userform.BirthDay" >
</md2-datepicker>
```

**Comment by josephserrano15** [comment]
No luck,

Error: Cannot find control with unspecified name attribute

I am using angular 4 by the way.

**Comment by ghost** [comment]
Can you create a plunkr? I am using md2 datetime picker with formGroup and it works perfectly.  So I do not think this is a bug but maybe a setup issue.

**Comment by josephserrano15** [comment]
Can you send me the way you use it if you don't mind?

Thanks,

**Comment by dharmeshpipariya-zz** [comment]
@josephserrano15 our plunkr template is available on -> [http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info](http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info) you can use it for creating an issue.

**Comment by josephserrano15** [comment]
I end up using this way, it is now working !

<md2-datepicker
                                  #BirthDay
                                  id="BirthDay"
                                  name="BirthDay"
                                  [type]="'date'"
                                  [placeholder]="'Birth Date'"
                                  [container] = "'inline'"
                                  [required]="true"
                                  formControlName="BirthDay">
                    </md2-datepicker>

**Comment by Swatantramishra1** [comment]
Hi  I am using md2 Datetime picker , every thing is working fine but when i am going to put it in dialogue it going behind of it please let me know how to fixe it
@dharmeshpipariya  Help me as soon as possible .

Thanks
