### ISSUE TITLE
Should we change .scss to .css

### ISSUE THREAD

**Issue by pmkeyan** [Promact/md2#182]
#### Bug, feature request, or proposal:
Bug, feature request, 

#### What is the expected behavior?

https://github.com/Promact/md2/blob/master/src/lib/accordion/accordionpanel.ts

I am very new to angular but i found in this code 
styleUrls: ['accordion.css'], 

but we have a file in the directory that called 'accordion.scss'. is it correct?.. or we have to change it as accodrion.css?.

#### What is the current behavior?
Like this I've found around 30 changes. Just ignore my questions if the code is right. Thanks

#### What are the steps to reproduce?

Should we change all the .scss to css or vice versa.?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.

#### What is the use-case or motivation for changing an existing behavior?
I am changing this .scss to .css for all the modules. so it could be resolved

#### Which versions of Angular, MD2, OS, browsers are affected?
Angular2

#### Is there anything else we should know?
-no-

**Comment by dharmeshpipariya-zz** [comment]
@pmkeyan the code implementation for scss is correct and we are also convert scss file to css using gulp-sass.
