### ISSUE TITLE
md2-datepicker stopped working after upgrading angular cli

### ISSUE THREAD

**Issue by V2NileshSukalikar** [Promact/md2#185]
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info

**Comment by dharmeshpipariya-zz** [comment]
@V2NileshSukalikar provide details proper as mentioned in issue template

**Comment by nichovski** [comment]
I'm facing the same issue.

The whole css is messed up after updating to angular 4.

![image](https://cloud.githubusercontent.com/assets/1162068/25759267/f7882280-31d1-11e7-88f0-b16fcc72d934.png)

![image](https://cloud.githubusercontent.com/assets/1162068/25759732/04d4bce4-31d4-11e7-8ba6-1b79b467f6c2.png)


Here are all my packages
{
  "name": "presentation",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.1",
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/compiler-cli": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.1.1",
    "@angular/platform-browser-dynamic": "^4.1.1",
    "@angular/platform-server": "^4.1.1",
    "@angular/router": "^4.1.1",
    "@types/dragula": "^2.1.30",
    "@types/lodash": "^4.14.64",
    "angular2-moment": "^1.3.0",
    "angular2-uuid": "^1.1.1",
    "core-js": "^2.4.1",
    "dragula": "^3.7.2",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.4",
    "md-toast": "0.0.1-alpha.1",
    "md2": "0.0.19",
    "moment-timezone": "^0.5.13",
    "ng2-ckeditor": "1.1.6",
    "ng2-currency-mask": "^4.0.2",
    "ng2-dragula": "^1.3.0",
    "ngx-sharebuttons": "^2.1.3",
    "rxjs": "^5.1.0",
    "typescript": "^2.3.2",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "4.1.1",
    "@types/jasmine": "2.5.47",
    "@types/lodash": "^4.14.54",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.2.34",
    "@types/node": "~7.0.18",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.1",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.6.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~3.0.4",
    "tslint": "~5.2.0",
    "typescript": "~2.3.2"
  }
}

Thanks

**Comment by dharmeshpipariya-zz** [comment]
@naspinski we have updated the issue, please go through the latest version of MD2
