### ISSUE TITLE
Provide your own link to template issue

### ISSUE THREAD

**Issue by laurentperroteau** [Promact/md2#187]
Please, provide your own link to template issue in [CONTRIBUTING.md](https://github.com/Promact/md2/blob/master/CONTRIBUTING.md#-submitting-an-issue), not from Material2 repo (I accidentally submitted my issue on Material2 :)

**Comment by dharmeshpipariya-zz** [comment]
@laurentperroteau are you talking about plunkr template?

**Comment by laurentperroteau** [comment]
No, I'm talking about the "issue" template at line 67:
> You can file new issues by providing the above information **here**

The link is "github.com/**angular/material2**/issues/new".

And thanks for the great datepicker
