### ISSUE TITLE
Datepicker: New Feature: Select and change year

### ISSUE THREAD

**Issue by leocaseiro** [Promact/md2#19]
Hi, I'd like to request a feature to change year.
I'm using the datepicker component for a date of birth field and it's very hard to my users navigating month by month.

My suggestion is to show a select/autocomplete field on click event into the year field.

Similar this component for angular 1: https://codepen.io/alenaksu/pen/eNzbrZ

Thanks

**Comment by dharmeshpipariya-zz** [comment]
change year feature added in md2@0.0.3 release.

**Comment by leocaseiro** [comment]
Thanks @dharmeshpipariya
