### ISSUE TITLE
md2 module not found during angular cli compile when referencing master branch

### ISSUE THREAD

**Issue by tw3** [Promact/md2#191]
#### Bug, feature request, or proposal:

Please update the project to support referencing the master branch.

#### What is the expected behavior?

According to the README:

> Playing with the latest changes from master is also possible
> 
> `npm install --save https://github.com/Promact/md2.git`

#### What is the current behavior?

The code installs but I see an error when running `ng serve`

` Cannot find module 'md2'.`

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info

Plunkr not relevant since this seems to be a build issue.

#### What is the use-case or motivation for changing an existing behavior?

Allow using code from the master branch.

#### Which versions of Angular, MD2, OS, browsers are affected?

Angular 4, MD2 master, Windows 8, Chrome

**Comment by dharmeshpipariya-zz** [comment]
@tw3 please look issue #133

**Comment by tw3** [comment]
Thanks and sorry for the duplicate bug
