### ISSUE TITLE
Pagination not working (angular 4 and table)

### ISSUE THREAD

**Issue by vicochips** [Promact/md2#194]
Hello !

I'm actually working with you solution, and I'm trying to create a table list. But I have  problem, the [rowsPerPageSet] is doing nothing, and the list is not refreshing at all.

Do you heard about this problem?

Regards,

**Comment by dharmeshpipariya-zz** [comment]
@vicochips There are `rowsPerPage` property instead of `rowsPerPageSet`, please refer [API Docs](https://github.com/Promact/md2/blob/master/src/lib/data-table/README.md) of table

**Comment by vicochips** [comment]
Hello !

When I put rowPerPage in the pagination I have this error: 

> 
> Error: Uncaught (in promise): Error: Template parse errors:
> Can't bind to 'rowsPerPage' since it isn't a known property of 'md2-pagination'.
> 1. If 'md2-pagination' is an Angular component and it has 'rowsPerPage' input, then verify that it is part of this module.
> 2. If 'md2-pagination' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("                      <td colspan="4">
>                                             <md2-pagination [ERROR ->][rowsPerPage]="[5,10,15]"></md2-pagination>
>                                         </td>


Regards,

**Comment by vicochips** [comment]
Hello,

Do you have any idea please, of why it is not working?

regards,

**Comment by dharmeshpipariya-zz** [comment]
@vicochips use `rows` instead of `rowsPerPage` as `<md2-pagination [rows]="[5,10,15]"></md2-pagination>`

**Comment by vicochips** [comment]
@dharmeshpipariya , I have the same error then with rows: 

zone.js:567 Unhandled Promise rejection: Template parse errors:
Can't bind to 'rows' since it isn't a known property of 'md2-pagination'.
1. If 'md2-pagination' is an Angular component and it has 'rows' input, then verify that it is part of this module.
2. If 'md2-pagination' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("                      <td colspan="4">
                                            <md2-pagination [ERROR ->][rows]="[5,10,15]"></md2-pagination>
                                        </td>

**Comment by dharmeshpipariya-zz** [comment]
@vicochips which version of md2 has you used in your application? and if you remove [rows] attribute then getting any issue?

**Comment by vicochips** [comment]
@dharmeshpipariya I'm using the last release 0.0.19.

without it, it is doing the same as rowsPerPageSet, I saw the pagination, but it is not working.
 If I have a list of 6, I see the 6 but I can't see 5 on the first page and 1 on the second page as it has to work. I only saw the all list on the same page.

Victor.

**Comment by dharmeshpipariya-zz** [comment]
@vicochips you have to set 'rowsPerPage' directive on `table` element

**Comment by vicochips** [comment]
@dharmeshpipariya , I know, I have done it, but it changed nothing 

Victor.

**Comment by dharmeshpipariya-zz** [comment]
@vicochips you have mentioned `rowsPerPageSet` property but you have to use `rowsPerPage` instead of `rowsPerPageSet`. and please create a plunkr of this issue so we can understand better.

**Comment by vicochips** [comment]
@dharmeshpipariya , I have tried both and both are not working^^'

Here is the full code of my table: 

`                 <table class="table table-striped"
                                       [md2Data]="filteredDemands"
                                       #md2="md2DataTable"
                                       [rowsPerPage]="5">
                                    <tbody>
                                    <div  *ngFor="let demand of filteredDemands" class="card u-clearfix">
                                        <div class="card-media">
                                            <img src="{{demand.created_by.img}}" alt="" class="card-media-img" />
                                            <a [routerLink]="['/user_profile', demand.created_by._id]">
                                                <div class="card-media-preview u-flex-center">
                                                    <svg fill="#ffffff" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                                                        <path d="M8 5v14l11-7z"/>
                                                        <path d="M0 0h24v24H0z" fill="none"/>
                                                    </svg>
                                                </div>
                                            </a>
                                            <span *ngIf="demand.created_by.is_company == false" class="card-media-tag card-media-tag-orange">{{demand.created_by.firstname}} {{demand.created_by.lastname[0] | uppercase}}</span>
                                            <span *ngIf="demand.created_by.is_company == true" class="card-media-tag card-media-tag-orange">{{demand.created_by.company_name | uppercase}} </span>
                                        </div>
                                        <div class="card-body">
                                            <div class="card-body-options-left">
                                                <h3 class="card-body-heading">{{demand.title}}</h3>
                                                <h3 class="card-body-content">{{demand.description}}</h3>
                                                <h3 class="card-body-content">{{demand.type}}</h3>
                                                <h3 class="card-body-content">Crée le {{demand.date |date:'d/M/y'}} à {{demand.date |date:'h:mma'}}</h3>
                                                <ul class="card-body-stars u-clearfix">
                                                    <p-rating [ngModel]="demand.created_by.average_mark" readonly="true" stars="5" [cancel]="false"></p-rating>
                                                </ul>
                                            </div>
                                            <div class="card-body-options">
                                                <a  class="card-button card-button-cta"  (click)="showDialog(demand._id)">
                                                    Haylp !
                                                </a>
                                                <a href="#/" class="card-button card-button-link">
                                                    More info
                                                    <span class="card-button-icon">
          <svg fill="#9C948A" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 4l-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8z"/>
          </svg>
        </span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <td colspan="4">
                                            <md2-pagination></md2-pagination>
                                        </td>
                                    </tr>
                                    </tfoot>
                                </table>`

**Comment by vicochips** [comment]
@dharmeshpipariya 

I have used both and both are not working :(

Here is a plunker of the table I use, I only put the html code on it so you can see the code but it is not beautiful of course^^

https://embed.plnkr.co/nOH8vyMCFB4BSh4MUEZz/

victor.

**Comment by dharmeshpipariya-zz** [comment]
@vicochips I can't get proper plunkr, you have put table code in the wrong place, you need to put table code in app component

**Comment by dharmeshpipariya-zz** [comment]
@vicochips i have created plunkr of data-table demo as ->http://plnkr.co/edit/fxiYMNMEx76ANn1xX3Np?p=preview

**Comment by vicochips** [comment]
@dharmeshpipariya 

I think I'm missing something, because I have copy paste your code, and it is not working on my app, I have 3 td, but I can't have 2 on one page, and the other one on the second page, It is displaying all in the same page , maybe my JSON is not good with this table.

**Comment by vicochips** [comment]
@dharmeshpipariya I HAVE FOUND the solution :D , I had to define a new data: any[ ] , and call it in my ngfor then it is working...

**Comment by dharmeshpipariya-zz** [comment]
@vicochips ok, then now I am closing this issue.
