### ISSUE TITLE
Can i have a bigger width on md-dialog ?

### ISSUE THREAD

**Issue by nobitahuang** [Promact/md2#196]
can i have a bigger width on md-dialog ? cause my styling not really affecting the size thanks

**Comment by jay-kamdar** [comment]
Please use this selector to change the width:
.cdk-overlay-pane .md2-dialog-panel{}

**Comment by nobitahuang** [comment]
its not working

**Comment by jay-kamdar** [comment]
Please show me your code.
It's working fine in mine.

**Comment by dharmeshpipariya-zz** [comment]
@chendzng set `.md2-dialog-panel { width: 1100px !important; }` style and modify with your width.

**Comment by l2radamanthys** [comment]
not found to modify a specific modal

**Comment by l2radamanthys** [comment]
i solved  

`
.md2-dialog-panel { 
    width: auto !important;
    min-width: 600px;
}
`

and in body add a div with custom size:

`<md2-dialog>
    <md2-dialog-title>Resultados Esperados</md2-dialog-title>
    <div style="width: 1100px"></div>
</md2-dialog>`

**Comment by jay-kamdar** [comment]
Its about priority of selector.
If .cdk-overlay-pane .md2-dialog-panel{} it is not working then use important keyword with css value.

**Comment by nelsonBlack** [comment]
have tried to change the width for a day without success please assist , have used all above examples no success
