### ISSUE TITLE
Problem with DatePicker

### ISSUE THREAD

**Issue by roni89** [Promact/md2#197]
Hi, I'm trying to use md2-datepicker, but I get the next error, when I use ng-serve:

**ERROR in Error encountered resolving symbol values statically. Calling function 'Md2DatepickerModule', function calls are not supported. Consider replacing the function or lambda with a
reference to an exported function.**

I searched for that a lot, but I didn't see any good solution or idea.

Angular CLI: 1.0.0
Angular: 2.4.10
DatePicker: 0.0.1-alpha.1

I tried to use the whole md2 package instead of md2-datepicker, but it didn't work because of angular animations (I couldn't use it in angular 2.4.10).

Do you have any idea for this problem? 

Thanks!

**Comment by dharmeshpipariya-zz** [comment]
@roni89 please upgrade your angular version with 4.\*.\* and you have to install @angular/animations package in your project

**Comment by Pranaeetha** [comment]
is this issue solved? i am still getting this error on initial compile 

below versions i am using

"@angular/animations": "^4.0.0",
"md2-datepicker": "0.0.1-alpha.1",

**Comment by krupa310** [comment]
@Pranaeetha Please use md2 package instead of md2-datepicker. For more info please read [document](https://github.com/Promact/md2/blob/master/README.md)
