### ISSUE TITLE
Bug: Datepicker Safari

### ISSUE THREAD

**Issue by leocaseiro** [Promact/md2#20]
Safari is not working for time and datetime, only date.

It might be something with the format.
I'll investigate deeply later. But, you can run the demo app and see `Nan`:

![screen shot 2016-10-04 at 1 40 53 pm](https://cloud.githubusercontent.com/assets/940070/19060952/3ce93914-8a38-11e6-8562-e12ef9c37ee7.png)

**Comment by dharmeshpipariya-zz** [comment]
@leocaseiro now we just targeting Latest version of Chrome Browser, we will provide support for all browser.
