### ISSUE TITLE
md2-datepicker incorrect date when using an iso date as value

### ISSUE THREAD

**Issue by jreyes** [Promact/md2#200]
#### Bug, feature request, or proposal:
When using a literal value ( coming from a rest endpoint ) that is in an standard ISO format without timezone for date only like **yyyy-MM-dd** the datepicker component calls the **coerceDateProperty** function that then it calls the **Date.parse** function which adds a timezone information to the date, and in mi timezone (EST or -05:00) then it displays a date less than it should display.

#### What is the expected behavior?
Display 04/04/1904

#### What is the current behavior?
It's displaying 04/03/1904

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/edit/WHQHka?p=preview

#### What is the use-case or motivation for changing an existing behavior?
When using literals to set the value like in my real case is using a FormGroup (formgroup.controls['dob']) to set the value of the datepicker, which contains a Date object but datepicker transforms the date to string and then back to date, this behavior is happening.

#### Which versions of Angular, MD2, OS, browsers are affected?
Angular 4.1.0, MD2 0.0.19, Firefox latest, Internet Explorer edge

**Comment by dharmeshpipariya-zz** [comment]
@jreyes we have fixed the issue
