### ISSUE TITLE
Where is system.config.js located to add

### ISSUE THREAD

**Issue by tcrowell83** [Promact/md2#201]
Where do i find the folder to add md2 in the system.config.js file?

Versions I'm running:
Angular 2.4.5
CLI: 1.0.0.beta.24
md2: 0.0.15

I want to be able to style and use the date-picker but can't import it correctly. Any help would be greatly appreciated

**Comment by tommykennedy** [comment]
If you save node modules locally when using NPM then you will find it within the local directory structure. My entry is at the following location.

 'md2':                        'node_modules/md2/bundles/md2.umd.js',
