### ISSUE TITLE
How can i set the minutes' time interval for the date picker?

### ISSUE THREAD

**Issue by shani7783** [Promact/md2#208]
Hello,
the current default is 1 minute,
I want an 5 minutes interval.
Thanks!
Shani

**Comment by shani7783** [comment]
Hello,
the current default is 1 minute, 
I want an 5 minutes interval.
Thanks!
Shani

**Comment by ali-kamalizade** [comment]
If i recall correctly there is a new input property you can use to achieve this (timeInterval).
If you're not using the latest version in package.json then you probably need to wait for a new published version (which I am also anticapating :) ).

**Comment by dharmeshpipariya-zz** [comment]
@shani7783 please refer [API Doc](https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md) of Datepicker, you have to use `timeInterval` to set minutes for time interval
