### ISSUE TITLE
Question about Date Picker Format

### ISSUE THREAD

**Issue by nichovski** [Promact/md2#210]
Can we use AM/PM in time picker? I tried with format="HH:mm a" but it is not working.

Thanks

**Comment by dharmeshpipariya-zz** [comment]
@nichovski now HH considering 24hrs time format, we will provide support for am/pm later

**Comment by dharmeshpipariya-zz** [comment]
@naspinski we have added support for it in the latest release.

**Comment by anishk4u** [comment]
Can we have AM/PM on the side of the picker popup (on the blue side which shows selected time). Also, is there a way to display either 12 hr or 24 hr format both on the side as well as inside the clock? Right now, there are two circles of values - one in 12 hour and inner one in 24 hour format.
