### ISSUE TITLE
Select: Support option groups

### ISSUE THREAD

**Issue by ali-kamalizade** [Promact/md2#213]
#### What is the expected behavior?
First of, I really like the MD2-Select, it's sleek and functional.
I'm missing a little feature, though: option groups.
In my case, I want to group option elements (e.g. locations by country).

#### What is the current behavior?
Currently, there's no way AFAIK to group options together.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info

#### What is the use-case or motivation for changing an existing behavior?
Option groups can be used to group similar or connected options.

#### Is there anything else we should know?
The Materialize.CSS framework has a feature like this: [http://materializecss.com/forms.html#select](url)

**Comment by dharmeshpipariya-zz** [comment]
duplicate issue #129
