### ISSUE TITLE
Datepicker is not working in modal

### ISSUE THREAD

**Issue by josephserrano15** [Promact/md2#218]
#### Bug, feature request, or proposal:

Date picker not showing when using a model( It actually gets display but in the background)
#### What is the expected behavior?

Date picker should show
#### What is the current behavior?

Datepicker is not showing

#### What are the steps to reproduce?

Create a datepicker in  modal

#### Which versions of Angular, MD2, OS, browsers are affected?

Latest

**Comment by dharmeshpipariya-zz** [comment]
duplicate issue #145

**Comment by nkescobar** [comment]
Hi, I have the same problem, Help Me!
