### ISSUE TITLE
Chips no longer works with pasting from the clipboard

### ISSUE THREAD

**Issue by TomJahncke** [Promact/md2#220]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When pasting from the clipboard the content is put into a chip(s).

#### What is the current behavior?
Creates a chip with empty content

#### What are the steps to reproduce?
Create a chip component and then try to paste into it from the clipboard.  FYI, this worked with version 0.17.

  <md2-chips
             [isRemovable]="true"
             item-text="name"
             [minChips]="2"
             [maxChips]="5"
             placeholder="Add"
  >
  </md2-chips>

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info
http://plnkr.co/edit/fLm7ezXdXxtGoDRBrUPu

#### What is the use-case or motivation for changing an existing behavior?
Need users to be able to paste in from their clipboard to create a chip. Ideally, the chip would take delimited input from the clipboard and make several chips, however, that is an enhancement. 

#### Which versions of Angular, MD2, OS, browsers are affected?
Angular ^4.0.0
MD2 0.19 (worked with 0.17)
Mac OS 10.12.5
Chrome (58) (Same issue in Safari)

**Comment by krupa310** [comment]
@TomJahncke will provide it in next build
