### ISSUE TITLE
Date picker ngmodel not working with type datetime. Value always comes as undefined

### ISSUE THREAD

**Issue by megamind2301** [Promact/md2#224]
#### Bug, feature request, or proposal:
ngmodel variable always gives undefined with type datetime

#### What is the expected behavior?
ngmodel variable should save value in ISO date format

#### Which versions of Angular, MD2, OS, browsers are affected?
Angular:4.\*.\* 
MD2: 0.0.21
OS: Ubuntu16.10

**Comment by raphaelbadia** [comment]
+1, same angular and md2 version with macOs

**Comment by megamind2301** [comment]
This is causing  #219 to me. I am setting max min values based on other md2-datepicker's values. And, if their value is not set, max and min doesn't make sense to main md2-datepicker.

**Comment by dharmeshpipariya-zz** [comment]
@Megamind2301 yes, exactly, if your issue is fixed then we close this issue.

**Comment by megamind2301** [comment]
@dharmeshpipariya I request you to work on this bug urgently. My product is about to go live in two days. It will be great help if fixed.

**Comment by MarcusCalidus** [comment]
@Megamind2301 @dharmeshpipariya 
I suppose this happens since "change" is not called when you click on the minute hand bubble. As long as you only set the hour hand and click "ok" the change event is called and the value is set.

**Comment by dharmeshpipariya-zz** [comment]
@Megamind2301 @MarcusCalidus I have fixed this issue in datepicker-dev branch as issue #227 will release soon.

**Comment by megamind2301** [comment]
@dharmeshpipariya  In v.0.0.24, Datepicker's container='dialog' is not working. Also, I am not able to set startView='year' as year view doesn't exist anymore.
In v<=0.0.22, Datepicker's startView is not working.

**Comment by dharmeshpipariya-zz** [comment]
@Megamind2301 refer [API docs](https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md) of Datepicker, we have replaced `container` property with `touchUi` and `startView='year'` it display year with months.
