### ISSUE TITLE
Timepicker text box value is not updating with value changes

### ISSUE THREAD

**Issue by Lasitha92** [Promact/md2#225]
#### Bug, feature request, or proposal:
The value shown in the text box is not updating after, value assigned to ngModel change. Placeholder value and time visible in the time-picker is updated as shown in following images. 

*In this image you can see that place holder contains 00:00 as the time value. But old value 02:10 is still visible.
![image](https://cloud.githubusercontent.com/assets/16875652/26710811/6f6999d8-477a-11e7-8e2c-3baf10aea8e0.png)
![image](https://cloud.githubusercontent.com/assets/16875652/26710901/dcdcf53c-477a-11e7-9f5e-3fedb1434518.png)

#### What is the expected behavior?
Text box value should show the same value as placeholder and time-picker.

#### What is the current behavior?
text-box value not updating with value changes

#### What are the steps to reproduce?
*add time-picker
*change the value assigned to the ngModel from the ts side

#### Which versions of Angular, MD2, OS, browsers are affected?
Angular version - 2.4.0
md2 version - 0.0.17
OS - Windows 10
Browser - chrome

#### Is there anything else we should know?
When I hide the timepicker after the value changed and show it again after about one second, value is correctly updated.
Please note that I can't update to Angular 4 as I am working on an old project.

**Comment by dharmeshpipariya-zz** [comment]
yes, textbox value change after completely selecting the time, I mean while you select the hour and minute both then it will reflect.

**Comment by Lasitha92** [comment]
But then the user will see old value as selected value till he click and check. Isn't it a bug?
