### ISSUE TITLE
Change even is not fired on datePicker

### ISSUE THREAD

**Issue by mrbinr** [Promact/md2#229]
#### Bug, feature request, or proposal:
Event on **datePicker type time** is not fired when you click new hour or minutes.

#### What is the expected behavior?
I have tested something like
 `<md2-datepicker formControlName="scheduleTimeOpen"  (change)="testChange()" type="time" placeholder="openning time"></md2-datepicker>`

#### What is the current behavior?
function testChange is not called.
I have tested same thing on **datePicker type date** and it works.

Best Regards,

Pascall

**Comment by ahirhasmukh** [comment]
@mrbinr Take latest `md2:0.0.22` It will work.

**Comment by dharmeshpipariya-zz** [comment]
@mrbinr it is duplicate issue #227
