### ISSUE TITLE
datepicker gets the focus when resizing the window

### ISSUE THREAD

**Issue by dimzeta** [Promact/md2#232]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When we resize the window, the focus shouldnt be on the datepicker input

#### What is the current behavior?
When we resize the window, the input has the focus automatically

#### What are the steps to reproduce?
Just go to the [demo page](http://code.promactinfo.com/md2/#/datepicker) and resize the window.

**Comment by dharmeshpipariya-zz** [comment]
@dimitribocquet we have fixed this issue with latest release of md2.
