### ISSUE TITLE
AOT Build Errors ver. 0.0.21

### ISSUE THREAD

**Issue by JacobFKlein** [Promact/md2#238]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

ng build --prod should compile with no errors

#### What is the current behavior?

Angular CLI returns the following error:
`ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 14:10 in the original .ts file), resolving symbol
mixinDisabled in {{path}}/node_modules/md2/core/common-behaviors/disabled.d.ts, resolving symbol _MdOptgroupMixinBase in {{path}}/node_modules/md2/core/o
ption/optgroup.d.ts, resolving symbol MdOptgroup in {{path}}/node_modules/md2/core/option/optgroup.d.ts`

#### What are the steps to reproduce?

Run the command: ng server --prod

**NOTE:** ng serve works without any issues

#### Which versions of Angular, MD2, OS, browsers are affected?
OS: Windows 10

angular: 4.0.0
angular/animations: 4.1.3
md2: 0.0.21

#### Is there anything else we should know?

I am using both the select and date-picker components in my project.

**Comment by dharmeshpipariya-zz** [comment]
@JacobK- we have fixed the issue in the latest release, please update it and comment here if you have any issue

**Comment by JacobFKlein** [comment]
@dharmeshpipariya It seems my issue is with the way I import the md2 modules, got it working on a new project now. Thanks for your help.
