### ISSUE TITLE
Datepicker datetime UI displays the wrong information

### ISSUE THREAD

**Issue by alexmba94** [Promact/md2#239]
#### Bug, feature request, or proposal:
When you click the datetime datepicker and get to the clock to select the time, the hours and minutes are displayed incorrectly.  Apart from not showing the month names in chrome, already mentioned [here](https://github.com/Promact/md2/issues/226) for which I still haven't found a solution.

#### What is the expected behavior?
You expect to see the clock hours from 1 to 12 in the outer circle, and from 13 to 00 in the inner circle, and the minutes from 00 to 55 in multiples of 5. And as you're clicking on the hours and minutes, you can see that what is displayed in the left blue column is exactly what you are choosing.  

![c1](https://user-images.githubusercontent.com/29369472/27079019-6202d93e-5036-11e7-9e6b-b3b0016c57ae.PNG)
![c2](https://user-images.githubusercontent.com/29369472/27079023-6399e83c-5036-11e7-8536-1785f3f1e0cd.PNG)

And when you finished selecting the time, the input displays what you picked correctly. It matches.

![c3](https://user-images.githubusercontent.com/29369472/27079033-6c551a0a-5036-11e7-9ec6-92b2b24ac173.PNG)

#### What is the current behavior?
This sort of behavior didn't happen before, but as I installed the version 0.0.23 with npm, the hours and minutes are displayed in another order. In the hours, the outer circles goes from 2 to 13 and the inner circle from 14 to 0 followed by another 00. And when you choose the hour, the left column displays one hour more than what you picked when you click on 00. So if you clicked on 00, it displays 01. This doesn't happen for all the other hours.  And then the minutes displayed are one minute more than they should be. 5 is 6, 10 is 11 and so on. The worst part is when you finished selecting the time, the input displays one hour and one minute earlier than what you chose. This is very confusing.

Here is an example picking the hour 00 and the minute 06 with the input; 

![1](https://user-images.githubusercontent.com/29369472/27079040-73af37ea-5036-11e7-86b4-3e6e4d138303.PNG)
![2](https://user-images.githubusercontent.com/29369472/27079043-750bf772-5036-11e7-9b6a-aed94b8052f5.PNG)
![3](https://user-images.githubusercontent.com/29369472/27079046-773e9126-5036-11e7-8aaf-b1e990900d8e.PNG)

Here is an example picking a different hour: 

![4](https://user-images.githubusercontent.com/29369472/27079052-7c314be2-5036-11e7-8d15-cad1870774bb.PNG)
![5](https://user-images.githubusercontent.com/29369472/27079058-7d678332-5036-11e7-8b47-41a86506bbda.PNG)
![6](https://user-images.githubusercontent.com/29369472/27079066-82412e12-5036-11e7-982d-c971f645bf6a.PNG)

#### What are the steps to reproduce?

You can reproduce what I tried to explain here:
http://plnkr.co/edit/kpvUGxBqutufayS83RlJ?p=preview

#### Which versions of Angular, MD2, OS, browsers are affected?
md2 0.0.23
npm 4.2.0
windows 7
angular 4.2.2
angular/cli 1.1.1

**Comment by pnotarangelo** [comment]
Same issue
md2 0.0.23
angular 4.0.1
angular cli 1.0.4

**Comment by svetq** [comment]
Same issue 
md2 0.0.24
angular 4.0.0
angular/compiler-cli 4.0.0

**Comment by janelett** [comment]
same issue

**Comment by shalugin** [comment]
@dharmeshpipariya Please check PR https://github.com/Promact/md2/pull/243

**Comment by alexmba94** [comment]
It still does the same thing though. I installed the latest version through npm and it still does the same thing.

md2 0.0.24
npm 4.2.0
angular 4.2.2
angular/cli 1.1.1

**Comment by dharmeshpipariya-zz** [comment]
@alexmba94 we have fixed that issue, will release it in next version

**Comment by shubham-k7** [comment]
@dharmeshpipariya When is the next release?

**Comment by dharmeshpipariya-zz** [comment]
yes
