### ISSUE TITLE
Select: Multi select with search header

### ISSUE THREAD

**Issue by ghost** [Promact/md2#241]
#### Bug, feature request, or proposal:
Bug/feature request

#### What is the expected behavior?
while Multi selecting  with search the already selected elements are not suppose to remove from select.

#### What is the current behavior?
while Multi selecting  with search the already selected elements are removing from select.

#### What are the steps to reproduce?
http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=preview

#### Steps to Reproduce.
1) Select any two elements(vadodra,Rajakot)
2) close the select
3) Search for "Goa"
4) Select "Goa"

The already selected items get removed.

**Comment by dharmeshpipariya-zz** [comment]
@prudhvireddy123 there are actually applied the filter to remove the select option from the array, so we can't access it inside the select component and while update select option, we update according to the model of it

**Comment by ghost** [comment]
@dharmeshpipariya Thanks. May you help me to make search will work with multi select.?

**Comment by dharmeshpipariya-zz** [comment]
@prudhvireddy123 it is difficult to manage search in multiple select, you can manage selected options while calling change event, but I suggest do not use search functionality with multiple select.

**Comment by ghost** [comment]
@dharmeshpipariya May be this will gives us more idea. Have a look https://github.com/softsimon/angular-2-dropdown-multiselect
