### ISSUE TITLE
Replace Angular material with md2

### ISSUE THREAD

**Issue by deepakzoto** [Promact/md2#244]
I want to replace angular material 2 with md2 in my codebase  due to treeshaking problem in angular material 2 . 

So I have following questions:
1. Does tree-shaking work in md2 ?
2. Is it possible to open a dialog  like this?
`let dialogRef = this.dialog.open(DialogResultExampleDialogComponent);`
3. Can we subscribe the result after closing the Dialog box?
 ```
   dialogRef.afterClosed().subscribe(result => {
    this.selectedOption = result;
     });
```
4.  Does it have disableClose property? 
`dialog.open(CheckPlansComponent, {disableClose: true});`

**Comment by dharmeshpipariya-zz** [comment]
@deepakzoto yes, you can use md2 library instead of material, but there are then way of dialog is different from material, Please refer [API Docs](https://github.com/Promact/md2/blob/master/src/lib/dialog/README.md)
