### ISSUE TITLE
Selected Time not displayed in textbox if picker type is set as time

### ISSUE THREAD

**Issue by kirtiesl** [Promact/md2#246]
Hello,
I am using below syntax in my html
<md2-datepicker type="time" touchUi="true" [openOnFocus]="true"></md2-datepicker>
But selected time is not displayed in the input box.  If I click on the time icon then my previous selected value is populated in input.

It is also not working here http://code.promactinfo.com/md2/#/datepicker

**Comment by dharmeshpipariya-zz** [comment]
@kirtiesl we have fixed this issue with the latest release, please go through it.
