### ISSUE TITLE
Update selection with a close button

### ISSUE THREAD

**Issue by OzsvathCsilla** [Promact/md2#247]
Hi,

Thank you for your work and effort regarding this nice library.
We are trying to use it, but our certain use-case requires that dropdowns be closed via a "Close" button, not only by the backdrop click. 
Could you make this possible?

Regards,
Csilla

**Comment by dharmeshpipariya-zz** [comment]
@OzsvathCsilla could you please explain in detail with an example?

**Comment by OzsvathCsilla** [comment]
![dropdown_close_by_click](https://user-images.githubusercontent.com/25619008/28010934-40339d00-6569-11e7-8495-2863cf4b5b1d.png)

Could you please add this button to dropdown header which trigger close event if i click on it?
