### ISSUE TITLE
I am using md2-tabs in my Angular 2 Application. Tabs are responsive in Chrome but not in Firefox. 

### ISSUE THREAD

**Issue by sunpasup** [Promact/md2#248]
#### What is the expected behavior?
Responsive behaviour in as in Chrome

#### What is the current behavior?
Not responsive in Firefox

<img width="1382" alt="screen shot 2017-06-22 at 2 54 22 pm" src="https://user-images.githubusercontent.com/24596204/27457870-29f683a2-575b-11e7-88e9-99fb1606519d.png">Firefox not responsive
<img width="1171" alt="screen shot 2017-06-22 at 2 54 56 pm" src="https://user-images.githubusercontent.com/24596204/27457871-29f88fc6-575b-11e7-8f22-493595984e24.png">  Chrome One responsive

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info

**Comment by dharmeshpipariya-zz** [comment]
@sunpasup it is working fine in FF
