### ISSUE TITLE
Chips ngModel push not working 

### ISSUE THREAD

**Issue by di3orlive** [Promact/md2#249]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
should working

#### What is the current behavior?
not working 

#### What are the steps to reproduce?
http://plnkr.co/edit/87seuqS7XGmEAYx04E4U?p=preview

#### Which versions of Angular, MD2, OS, browsers are affected?
last/last/win10/chrome last

#### Is there anything else we should know?
no

**Comment by krupa310** [comment]
@di3orlive If you want to add chips from autocomplete, then you need to bind your list value to the "autocompleteDataList".
please refer [document](https://github.com/Promact/md2/tree/master/src/lib/chips).

**Comment by di3orlive** [comment]
@krupa310 same thing http://plnkr.co/edit/NVRCnlOeFcBILzY4avNg?p=preview
press enter and nothing happens with chips http://prntscr.com/fo6ppl
but arrays is not empty

**Comment by dharmeshpipariya-zz** [comment]
@di3orlive there are no `keyup` event in chips component, please refer Example of [chips](https://github.com/Promact/md2/tree/master/src/demo-app/chips)

**Comment by di3orlive** [comment]
@dharmeshpipariya so its impossible to solve this problem using this chips ?

**Comment by krupa310** [comment]
@di3orlive we have designed 2 type of chips
1. user can add chips by using input
2. user can add chips by selecting item from autocomplete list
