### ISSUE TITLE
Contrast between font color and background color 

### ISSUE THREAD

**Issue by j-tee** [Promact/md2#252]
![datepicker](https://user-images.githubusercontent.com/5064641/27659582-f6947df2-5c4b-11e7-8492-26e4d83e6c60.png)
Hi folks.
Any ideas on how I get the font color and background color of md2-datepicker to (for want of better word) contrast?

#### Which versions of Angular, MD2, OS, browsers are affected?
Angular 4 md2

**Comment by krupa310** [comment]
@j-tee , It seems like you have given background-color to the table. could you please provide plunkr demo?
