### ISSUE TITLE
Custom Id for md2-datepicker

### ISSUE THREAD

**Issue by shubham-k7** [Promact/md2#254]
Hi, As far as I can see, there isn't a way to add a Custom ID to the <md2-datepicker> component!
I tried doing it like
```js
<md2-datepicker id="customID"></md2-datepicker>
```
You can find a working example of the datepicker [here](http://plnkr.co/edit/tu7qqRV6TA8kKh4AqMsC?p=preview) with fixed id.
However, the id remains the one you assign in your file here..
```js
  /** The id for the datepicker calendar. */
  id = `md2-datepicker-${datepickerUid++}`;
```
Is there a way we can input() **id** attribute of the md2-datepicker object?
Please guide.
Thanks for these nice components!

**Comment by krupa310** [comment]
@shubham-k7 will provide it in next build
