### ISSUE TITLE
Disabled dates on Datepicker (Month mode) can still be selected

### ISSUE THREAD

**Issue by jedcua** [Promact/md2#269]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dates on Datepicker on Month mode with defined minimum date must be disabled.

#### What is the current behavior?
Invalid dates can still be selected

#### What are the steps to reproduce?
```html
<md2-datepicker fxFlex type="month" mode="portrait" touchUi="true" placeholder="From" [min]="minDate" [(ngModel)]="fromDate"></md2-datepicker>
```

```typescript
export class GenerateDatesComponent implements OnInit {
  // ...
  constructor(
    public dialog: MdDialogRef<GenerateDatesComponent>
  ) {
    this.minDate = new Date();
    this.fromDate = this.minDate;
  }
}
```

The invalid dates appears disabled:
![screenshot - friday 04 august 2017 - 11 16 54 pht](https://user-images.githubusercontent.com/11945463/28952824-7270b5d6-7906-11e7-99e5-2719413b9af2.png)

When I can still click on them and it will be selected:
![screenshot - friday 04 august 2017 - 11 17 33 pht](https://user-images.githubusercontent.com/11945463/28952840-88b2bbaa-7906-11e7-8a1b-7f4325ce2cab.png)

#### What is the use-case or motivation for changing an existing behavior?
Disabled dates should not be selected.

#### Which versions of Angular, MD2, OS, browsers are affected?
`Angular 4.0.0`
`md2 0.0.26`
on `Ubuntu 14.04`
using `Google Chrome 57.0.2987.133`

#### Is there anything else we should know?
You guys are awesome.

**Comment by krupa310** [comment]
@jedcua will provide it in next build
