### ISSUE TITLE
[Question] Md2Autocomplete and textChange emit old value

### ISSUE THREAD

**Issue by maratoss** [Promact/md2#272]
Hi. Just a question.
When i subscribed on Md2Autocomplete.textChange i am waiting for actual value but i see there is previous result.
e.g.
i typed 'Hello', but emitted value is 'Hell'
http://plnkr.co/edit/mXFOxwDB7jFmeotrausc?p=preview

And one more:
When i key 'left arrow' or any other keys which do not affect somehow on text, the emit is performed.
But i believe that emit should not be performed.

**Comment by krupa310** [comment]
@maratoss will update it in next build

**Comment by maratoss** [comment]
@krupa310 

Thanks.
I see you left the emit value in keyDown handler and now we have it also in keyUp handler => it will emit twice, is it correct behavior?

And what about second point? 
I guess it should emit only when text is really changed, but as i said it emits even if you push any arrows or Esc Or Enter etc...

**Comment by krupa310** [comment]
@maratoss  no it should trigger only once(on KyeUp). I had mistakenly keep it in KeyDown.

For your second point:
Currently, we are not planning for that.
