### ISSUE TITLE
Select component doesnt accept 0 and false values(ngModel) in md2-option

### ISSUE THREAD

**Issue by rushi216** [Promact/md2#275]
https://github.com/Promact/md2/blob/4f4047751d980ce6a74acbf32cab1476a465afa7/src/lib/select/select.ts#L578

Because of above line it is not selecting option whose value is 0 or false. We might need to update `option.value && this.equals(option.value, value)` to `option.value != null && option.value != undefined && this.equals(option.value, value)`

**Comment by ali-kamalizade** [comment]
I can confirm that 0 doesn't work. This one gave me headaches as I've thought I was doing something wrong.

**Comment by krupa310** [comment]
updated in latest version
