### ISSUE TITLE
md2@0.0.9 fails with angular-cli AoT compiler

### ISSUE THREAD

**Issue by Mufasa** [Promact/md2#28]
I have reported this in the angular-cli GitHub: https://github.com/angular/angular-cli/issues/2954

**Comment by Merraclius** [comment]
Hello, @dharmeshpipariya 

What with that bug? How do you think, when can we expect fixes?

**Comment by dharmeshpipariya-zz** [comment]
We have fixed this issue with release md2@0.0.7,
comment here if you have an issue

**Comment by Mufasa** [comment]
Just tried with md2@0.0.7 - same issue.
I have amended the title of this issue to reflect that.

**Comment by Mufasa** [comment]
Just tried with md2@0.0.9 - same issue.
I have amended the title of this issue to reflect that.

**Comment by metaory** [comment]
**0.0.10-2** stills fails, 
I think problem is lack of metadata.json

**Comment by dharmeshpipariya-zz** [comment]
We have fixed this issue with release md2@0.0.10-3,
comment here if you have an issue
