### ISSUE TITLE
md2@0.0.6 md2-select not work in Firefox and IE11

### ISSUE THREAD

**Issue by hydraslay** [Promact/md2#29]
The issue is that when I select an option , the selected value will not update.
    <md2-select [(ngModel)]="selectedCategory" placeholder="category">
      <option *ngFor="let i of categories" [value]="i">{{i}}</option>
    </select>
 
even I use:
   <md2-select [(ngModel)]="selectedCategory" (change)="onChange($event)" placeholder="category">
      <option *ngFor="let i of categories" [value]="i">{{i}}</option>
    </select>

    onChange(newValue) {
      this.selectedCategory= newValue;
    }

I ran the demo on Chrome, Firefox, IE11 and the result is only work on chrome.

**Comment by dharmeshpipariya-zz** [comment]
use `md2-option` instead of `option` tag and refer [md2-select](https://github.com/Promact/md2/blob/master/src/lib/select/README.md)
