### ISSUE TITLE
Datepicker: Date entered manually with keyboard

### ISSUE THREAD

**Issue by ilianiv** [Promact/md2#38]
It would be nice if there is datepicker mode that enables entering a date from keyboard

**Comment by nlgi** [comment]
"up" :)
Is itplanned in a future release? It would fix another bug: You can't delete the date (clear the field)

**Comment by dharmeshpipariya-zz** [comment]
yes, we will provide this feature, but now we haven't planned.

**Comment by pfeigl** [comment]
Very nice idea, something we are also looking for! Probably part of the work is already done with the PR from #106 

Looking forward to seeing this work :)
