### ISSUE TITLE
Datepicker: set min/max date check current date

### ISSUE THREAD

**Issue by ilianiv** [Promact/md2#39]
It is strange that date not in range can be selected if:

1. Select a date (ex. 2016-11-15)
2. Change max input to date before selected (ex. 2016-10-15)
3. Selected date is out of new range

I think expected behaviour should be moving selected date to closest one in range (ex. 2016-10-15)

**Comment by dharmeshpipariya-zz** [comment]
@ilianiv we can not prevent it
