### ISSUE TITLE
Toast is declaring variables and not using them

### ISSUE THREAD

**Issue by michaeljota** [Promact/md2#40]
toast.component.ts

'Inject' is declared but never used.
'Optional' is declared but never used.

I don't know if this is intentional, or not. Just to point it. Also, you might want to use [Codelyzer](http://codelyzer.com/) with the proper rules.

**Comment by dharmeshpipariya-zz** [comment]
thank's @michaeljota we will update it soon.

**Comment by michaeljota** [comment]
This errors are actually being threw by the compiler, no the linter. New configuration options are available in Typescript 2, this are: `noUnusedParameters` and `noUnusedLocals`. Because of this are set in my configuration, they are impeding me to build with this. 

Can I make a PR commenting those out or removing them? Are they necessary?

EDIT: The source files are really necessary in the npm module? I think they don't. The `.js` , `map.js` and `d.ts` should be enough.

**Comment by michaeljota** [comment]
@dharmeshpipariya Yeah, the error it's caused because the source file it's being distributed in the module, and it shouldn't. It's the only source file in the module, and if I delete it everything works out just fine.

**Comment by dharmeshpipariya-zz** [comment]
@michaeljota we have already started work on it. you can get it in next release.
