### ISSUE TITLE
Demo Confirm Dialog not working

### ISSUE THREAD

**Issue by michaeljota** [Promact/md2#41]
The demo of Confirm Dialog does not work. Show a dialog, but with not buttons to either confirm or cancel, as I guess it suppose to work. 

![screen](https://cloud.githubusercontent.com/assets/10507776/20308689/70a1eed2-ab1b-11e6-9528-bd69ffc775c5.png)

**Comment by dharmeshpipariya-zz** [comment]
we haven't implemented confirm or alert type dialog, we have just implemented common dialog for all types. we will provide its support later.

**Comment by dharmeshpipariya-zz** [comment]
we have updated the demo Confirm Dialog
