### ISSUE TITLE
select and datepicker not working in IE11

### ISSUE THREAD

**Issue by Mufasa** [Promact/md2#43]
I am using these two components in my angular 2 app and they seem to work fine in Chrome, FireFox and Safari. However they seem to be broken in IE11. When I click in the component it displays the selectable items but when I click on an item to select it then nothing appears to have been selected. I tried loading your demo site in IE11 and even with that I get the same broken behaviour under IE11.

I am using **md2@v0.0.10** and **angular@2.2.2**

**Update**
I have discovered that if I use the keyboard and press enter to select items then that seems to work. So its only mouse selection that seems to have an issue.

**Comment by acy2yiu** [comment]
I found that the onBlur event somehow got triggered when you click on the popup menu in the Select control, which sets the isFocused variable to false immediately, forcing the menu to close before any changes is made in the list.  I believe it's an IE issue and it's probably not very difficult to implement a workaround.

**Comment by acy2yiu** [comment]
Problem can be solved by adding a mousedown event in multiselect.js

        Md2Multiselect.prototype.onMouseDown = function (event) {
            event.preventDefault();
        };
...
        __decorate([
            core_1.HostListener('mousedown', ['$event']),
            __metadata('design:type', Function),
            __metadata('design:paramtypes', [MouseEvent]),
            __metadata('design:returntype', void 0)
        ], Md2Multiselect.prototype, "onMouseDown", null);

**Comment by user123x1** [comment]
I am interested in using the datepicker unfortunately due to the bug state above for IE 11 i am unable to do so. I know there is a new datepicker implementation in the datepicker-dev branch. When would this be merged into main branch? Anytime soon?

great work!
thanks,

**Comment by dharmeshpipariya-zz** [comment]
@user123x1 will try to release updated datepicker component in this month.

**Comment by mogalethali** [comment]
any update?

**Comment by EndarValuk** [comment]
@acy2yiu thank you. Your hardcoded fix helped me :)
Added lines both in multiselect and datepicker.
