### ISSUE TITLE
.metadata.json for AoT

### ISSUE THREAD

**Issue by metaory** [Promact/md2#44]
> Third party libs have to be AoT-ed before they can be integrated in an AoT compiled application. The third party library should publish JS files, .d.ts files and metadata.json files

[Getting your Angular 2 library ready for AoT](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.htgx9968y)

[AoT compile err](https://github.com/angular/angular/issues/11262)

**Comment by metaory** [comment]
Managed to generate the **.metadata.json**  from this repo **gulp :build:components:ngc** 
why these .metadata.json files not included in packaged release?

that solved the missing .metadata.json files, 

these properties should be public as well, 
    Property 'top' is private and only accessible within class 'Md2TooltipComponent'.
    Property 'left' is private and only accessible within class 'Md2TooltipComponent'.
    Property '_isVisible' is private and only accessible within class 'Md2TooltipComponent'.

this is gonna work.
will make a pr soon

**Comment by metaory** [comment]
there is another problem with *MouseEvent* now, will look at this later
> MouseEvent  is not defined

**Comment by metaory** [comment]
thanks @dharmeshpipariya  for 66c03f6 
this fixed the .metadata.json issue for AoT build,

I had to make almost all privates to public, for AoT build, not sure how badly that would pollute the global namespace, but that's what AoT build wants! 

the Universal build however is failing terribly all over the place, and its mainly pending 
angular/material2#308 

I'll just close this issue

**Comment by dharmeshpipariya-zz** [comment]
We have fixed this issue with release md2@0.0.10-3,
comment here if you have an issue
