### ISSUE TITLE
AoT compiler failing with md2@0.0.11

### ISSUE THREAD

**Issue by aroop** [Promact/md2#47]
AOT compilation failed for my app with the following errors.

```
dist/tmp/node_modules/md2/autocomplete/autocomplete.ngfactory.ts(235,44): error TS2339: Property '_control' does not exist on type 'Md2Autocomplete'.
dist/tmp/node_modules/md2/autocomplete/autocomplete.ngfactory.ts(235,91): error TS2339: Property '_control' does not exist on type 'Md2Autocomplete'.
dist/tmp/node_modules/md2/autocomplete/autocomplete.ngfactory.ts(253,48): error TS2339: Property '_onBlur' does not exist on type 'Md2Autocomplete'.
```

I guess the following lines are the rootcause
https://github.com/Promact/md2/blob/master/src/lib/autocomplete/autocomplete.ts#L66
https://github.com/Promact/md2/blob/master/src/lib/autocomplete/autocomplete.ts#L69

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.12,
comment here if you have an issue
