### ISSUE TITLE
Not close custom dialog When I have click on submit button(Submit form).

### ISSUE THREAD

**Issue by ahirhasmukh** [Promact/md2#48]
I have submit form on submit button click. but I have use custom function like `saveArea(areaForm.value,areaForm.valid)`. and In `typescript` file in function has `if..else` condition.`if` form submitted successfully submit and `else` doesn't want to close dialog and error message display..

I want to close dialog In `IF`. so please help. I have through `MD2` documents but I cant found that.

I know about some methods of dialog
In `.ts` file 
 `show(dialog: any) { dialog.show(); }`
`close(dialog: any) { dialog.close(); }`

but it's not working it. I thought some custom methods.

========  HTML code  =======

```
<md2-dialog #newArea title="Create a new area">
   <form [formGroup]="areaForm" novalidate (ngSubmit)="saveArea(areaForm.value,areaForm.valid)">
        <div class="col-md-12">
           <md-input formControlName="name" class="form-control" type="text" placeholder="Enter area name"></md-input>
        </div>
        <div class="clearfix"></div>
        <md2-dialog-footer>
            <button button type="button" (click)="newArea.close()" [ngClass]="'modal-cancel-btn'">Cancel</button>
           <button button [ngClass]="'modal-save-btn'">Create</button>
        </md2-dialog-footer>
    </form>
</md2-dialog>
```

======= typescript code ========

```
saveArea(value: any, isFormValid: boolean) {`
    console.log(value);
    this.isFormSubmitted = true;
    this.isFormInvalid = isFormValid;
    if (isFormValid) {
      if (this.selectedArea == null) {
        this.donationAreaManagementService.addArea(value).subscribe(result => {
          this.initialize()
        })
      } else {
        let body = {
          "name": value.name,

        }
        this.donationAreaManagementService.editArea(this.selectedArea.areaId, body).subscribe(result => {
          this.initialize()
        })
      }
    }
  }

```  

![dialog png 1366x768](https://cloud.githubusercontent.com/assets/8941195/21482564/9ca593f8-cb9b-11e6-8ce0-b123ef73f41b.png)

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya  please help me on this issue

**Comment by dharmeshpipariya-zz** [comment]
Refer https://github.com/Promact/md2/tree/master/src/lib/dialog and demo code https://github.com/Promact/md2/tree/master/src/demo-app/dialog

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya I have refer already bro. but I haven't found that issue. I have shared my code so please review and let me know

**Comment by dharmeshpipariya-zz** [comment]
@smartHasmukh there are two ways to close dialog as already I have mentioned in my demo as well as readme.md of dialog component,
1. First way, As you have already used over click event of cancel button of dialog in above HTML code.
2. Second way, define reference variable same as you have assigned and pass it through your function as:
==== HTML ====
<md2-dialog #newArea title="Create a new area">
        <md2-dialog-footer>
           <button (click)="saveArea(newArea)">Create</button>
        </md2-dialog-footer>
    </form>
</md2-dialog>

==== Typescript ====
saveArea(newArea: Md2Dialog) {
//your code with conditions
newArea.close();
}

**Comment by ahirhasmukh** [comment]
It's working now. Thanks @dharmeshpipariya

**Comment by LeiwenL** [comment]
I have an other question, how do you catch in typescript the event close dialog ?! Someone can help me ? Thanks!

**Comment by dharmeshpipariya-zz** [comment]
@LeiwenL We developed the dialog is as service, so there are not open or close events. you can catch close dialog event while you call close method of dialog as `dialog.close();`

**Comment by ahirhasmukh** [comment]
@LeiwenL If you close on form submitted event so you should pass argument reference name of dialog. like form submit event `(ngsubmit)="onsubmit(newdateform)" ` and Typescript `onsubmit(dialog:any){this.close()}`

`newdateform` is a dialog reference name

**Comment by LeiwenL** [comment]
Thank you, but I need to know when user click on the close icon in the header section, there is a solution ?

**Comment by dharmeshpipariya-zz** [comment]
@LeiwenL we have added events please refer [Md2Dialog](https://github.com/Promact/md2/blob/master/src/lib/dialog/README.md)

**Comment by LeiwenL** [comment]
Great !! Thank you, but how can I catch the event onClose in my typescript? I can't find this in the md2dialog doc :/

**Comment by dharmeshpipariya-zz** [comment]
@LeiwenL its very simple, it binds in the same way as other events, as:
HTML
`<md2-dialog #customDialog (onClose)="onCloseDialog($event)" title="dialog title">
    Body Content...
</md2-dialog>`

TS
`onCloseDialog(event:any){
// your code
}`

**Comment by LeiwenL** [comment]
Oh ! Ok I understand I'm still a beginner in Angular2, in fact it's easy 😄 , thank you so much !
