### ISSUE TITLE
DateTime Picker Internationalization

### ISSUE THREAD

**Issue by mcauzeill** [Promact/md2#50]
DateTime Picker UI is in English. Would it be possible to implement internationalization, please?

**Comment by cristi200915** [comment]
you can modify the source code and translate to your language in the md2module folder datepicker>datepicker.js modify the arrays 
![captura de pantalla 153](https://cloud.githubusercontent.com/assets/5085449/22599101/9ee03a8e-ea03-11e6-9e6f-6f42f12deb9d.png)

**Comment by daright** [comment]
you should never modify libraries

**Comment by cristi200915** [comment]
Daright another way for changue the languague and keep good practices ?

**Comment by dharmeshpipariya-zz** [comment]
refer #122
