### ISSUE TITLE
When I have to open md-select and press 'A' key then move focus should be on 'A' string like 'Apple'

### ISSUE THREAD

**Issue by ahirhasmukh** [Promact/md2#61]
![focus](https://cloud.githubusercontent.com/assets/8941195/21981866/78d833f2-dc0f-11e6-9fe5-b269b7dea499.png)

Right now focus on 'Mango'. After press key 'A' I wanted to know second screenshot

![plunker](https://cloud.githubusercontent.com/assets/8941195/21981883/8a0a4e62-dc0f-11e6-9902-f103139360eb.png)

I wanted to need same as in angular2 like - [AngularJs Demo](http://codepen.io/craigsh/pen/GorpVV)

**Comment by dharmeshpipariya-zz** [comment]
This feature will provide later.

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya  Can you know me time to provide this feature please?

**Comment by dharmeshpipariya-zz** [comment]
Now we haven't plan about this feature, so it will be available up to March 2017 or you can send PR of it.

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya - PR means?

**Comment by dharmeshpipariya-zz** [comment]
pull request
