### ISSUE TITLE
can anyone explain how to import separate component from your md2 module?

### ISSUE THREAD

**Issue by Muthu2020** [Promact/md2#66]

**Comment by MigCoder** [comment]
For example, the datetime picker component is in Md2DatepickerModule, so below code will only import this module to your application:

import { Md2DatepickerModule }  from 'md2'
@NgModule({
    imports: [
        Md2DatepickerModule.forRoot()`
    ],
    bootstrap: [AppComponent]
})

**Comment by Muthu2020** [comment]
Exactly...What you mentioned in above comment only I used in my project.

**Comment by gozeon** [comment]
@MigCoder @Muthu2020 
```typescript
import { Md2DatepickerModule, MdNativeDateModule } from 'md2';

@NgModule({
  imports: [
    Md2DatepickerModule,
    MdNativeDateModule,
    ...
  ],
  bootstrap: [AppComponent]
})
```
[demo](http://embed.plnkr.co/1dfwyg/)
