### ISSUE TITLE
Format of datepicker not being used on render.

### ISSUE THREAD

**Issue by nlubin-lv** [Promact/md2#69]
The passed format to the datepicker only is being used when a new date is selected, when it first loads it uses the default format.

```
    dateFormat = 'MM/DD/YYYY';
```

Template:

```
    <md2-datepicker
       [formControlName]="question.key"
       [id]="question.id"
       [type]="question.type"
       [format]="dateFormat"
   ></md2-datepicker>
```

**Comment by nlubin-lv** [comment]
It seems like `writeValue` is being called before the `format` is set from the component so it uses the default.

Right now in my app I am proxying the `writeValue` for the DatePicker to have the correct format (as a hack) before this gets fixed in the library.

--------------

This is my _current_ hack:

```
const _dateFormat = 'MM/DD/YYYY';
const writeValue = Md2Datepicker.prototype.writeValue;

// need to override this function because the format is set wrong here
Md2Datepicker.prototype.writeValue = function (value): void {
    this.format = _dateFormat;
    writeValue.call(this, value);
};
```

**Comment by yuzhva** [comment]
:heavy_plus_sign::one: I had the issue in my demo project.
