### ISSUE TITLE
Need to tab 2x to go to next input from datepicker

### ISSUE THREAD

**Issue by nlubin-lv** [Promact/md2#71]
If you click into an input you need to press TAB 2 times in order to move onto the next inout in the form (instead of the expected once)

**Comment by nlubin-lv** [comment]
I fixed this in all Mac browsers aside from FireFox by adding this to my extended Component:

```
    @HostListener('keydown', ['$event.keyCode', '$event'])
    _keydownEvent(keyCode: string, event: KeyboardEvent) {
        if (!_.isEqual(keyCode, TAB)) {
            this._handleKeydown(event);
        }
    }
```

**Comment by dharmeshpipariya-zz** [comment]
@nlubin-lv could you explain, why we need to press 2x tab key instead of the single press?

**Comment by nlubin-lv** [comment]
Sorry I think I was misunderstood.

There seems to be a bug that you have to press tab twice to leave the date picker to go to the next input instead of once.
