### ISSUE TITLE
I want to datepicker open on button click event

### ISSUE THREAD

**Issue by ahirhasmukh** [Promact/md2#72]
I want to open datepicker on focus and button click event. so please let me know open and close event of datepicker. same as dialog(Open / close event)

Please help me @dharmeshpipariya @mmrath @leocaseiro @rushi216 @chintans @AsherBarak

**Comment by aminsmartsense** [comment]
Hello,

I am facing same issue in my project and still not found any solution in md2-module for that so please help me in this.
@dharmeshpipariya @mmrath @smartHasmukh @chintans @rushi216 @leocaseiro 

Thank you.

**Comment by ahirhasmukh** [comment]
I have checked but haven't worked yet

**Comment by dharmeshpipariya-zz** [comment]
@smartHasmukh we have fixed issue in our code, you can find it on next release

**Comment by ahirhasmukh** [comment]
Issue occured #91

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya Issue occured
