### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by ISevenSinsI** [Promact/md2#73]
On several pages we have Md2 Datatable built in which are using "md2SortBy".
We noticed that the buttons in our menu trigger the sort in some way we can't, and is hard to explain.

![screen shot 2017-02-02 at 09 35 12](https://cloud.githubusercontent.com/assets/9038868/22542219/0a59db28-e92b-11e6-8651-c11f75220884.png)

Steps:
**Activate sorting** 
As seen in the above screenshot, we set the active sorting on the user's id. Everything seems to go fine until here.

The code is set up like this:

```
<thead>
	<tr>
		<th md2SortBy="dateadded">Creation date</th>
		<th md2SortBy="isnl">IsNL</th>
		<th md2SortBy="transaction_type_string">Type</th>
		<th md2SortBy="userid">User ID</th>
		<th md2SortBy="money">Amount</th>
		<th>Paid out</th>
		<th>In progress</th>
		<th>Processed</th>
		<th md2SortBy="invoicenr">Invoice nr.</th>
		<th>Invoices</th>
		<th>Export</th>
	</tr>
</thead>
```

![screen shot 2017-02-02 at 09 40 20](https://cloud.githubusercontent.com/assets/9038868/22542353/ad66b00c-e92b-11e6-8a37-2ea5bf620a4c.png)
**Hover / Mouse leave on buttons.**
Notice the buttons in the right top. These are normal buttons with no special events bound to it which in our opinion could trigger the md2SortBy function.
But still, if you look at how the rows are sorted now, there's a slight difference (Notice the dates)

Code of the buttons:

```
<md-toolbar>
	<span>
	  	<button md-icon-button click="sidenav.toggle()">
	        <md-icon>menu</md-icon>
	    </button>
	</span>
	<!-- This fills the remaining space of the current row -->
	<span class="flex-fill"></span>
	<span>
	  	<button md-icon-button [md-menu-trigger-for]="friends">
	        <md-icon>group_add</md-icon>
	    </button>
	    <md-menu #friends="mdMenu">
	        <button md-menu-item> 2 new friends </button>
	        <button md-menu-item> 4 new messages </button>
	        <button md-menu-item> 3 friend requests </button>
	    </md-menu>
	    <button md-icon-button>
	        <md-icon>mail</md-icon>
	    </button>
	    <button md-icon-button>
	        <md-icon>keyboard</md-icon>
	    </button>
	    <button md-icon-button>
	        <md-icon>notifications</md-icon>
	    </button>
	    <button md-icon-button (click)="logout()" mdTooltip="Logout">
        	<md-icon>power_settings_new</md-icon>
        </button>
    </span>
</md-toolbar>
```

This happens for several tables in our application, while we see no reason why the sorting should change on mouse-enter/mouse-leave of these buttons.
Any help or information would be appreciated!

**Comment by SjorsHartwijk** [comment]
+1

**Comment by danik121** [comment]
+1

**Comment by Rodge80** [comment]
+1

**Comment by dharmeshpipariya-zz** [comment]
@ISevenSinsI, we have checked but not able to generate it our end. data-table is working properly with it's all functionalities. could you please provide plunker demo?

**Comment by shalugin** [comment]
Demo: https://github.com/shalugin/md2-datatable-sample

There is no bug without material style (no hover effect).

**Comment by shalugin** [comment]
Step to reproduce on demo http://code.promactinfo.com/md2/#/datatable
1. Sort by Age asc/desc
1. Click on "Filter By Name"
1. Click outside table

**Comment by shalugin** [comment]
@dharmeshpipariya is my pull request incorrect?

**Comment by dharmeshpipariya-zz** [comment]
@shalugin we have reviewed and merged it
