### ISSUE TITLE
Tooltip doesn't hide on Mozilla Firefox. and  --webkit-- browsers as well

### ISSUE THREAD

**Issue by ahirhasmukh** [Promact/md2#75]
When I have click on add dialog button then tooltip not working(hide) on all browsers.

I have attached 2 screenshot please check it. I hope you will understand.

**On button hover - Showtooltip(working fine)**
![tooltip1](https://cloud.githubusercontent.com/assets/8941195/22550336/8da0310e-e975-11e6-9a7b-201986c208d8.png)

**But doesn't hide tooltip(Issue on open dialog or redirect to another page).**
![tooltip2](https://cloud.githubusercontent.com/assets/8941195/22550417/f1e5527a-e975-11e6-8529-caffa5b93039.png).

@dharmeshpipariya @chintans  @rushi216   please help me try to resolved above issue

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya  did you checked?

**Comment by dharmeshpipariya-zz** [comment]
@smartHasmukh yes we have fixed this issue. will release in next build.

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.14,
comment here if you have an issue

**Comment by ahirhasmukh** [comment]
Working fine Thank you @dharmeshpipariya
