### ISSUE TITLE
can anyone help me out to configure the md2-tags input module as separate

### ISSUE THREAD

**Issue by Muthu2020** [Promact/md2#79]
I have tried to install using the below command 

npm install md2-tags

After installing and configuring the md2-tags,it thrown an error message that @angular2-material/autocomplete/autocomplete.js(404 error) in  md2-tags.js.I think md2-tags is not properly compiled as js.

Anyone check it and let me know ASAP.

**Comment by dharmeshpipariya-zz** [comment]
@Muthu2020 use 'npm install md2' instead of 'npm install md2-tags' and there are all components are available
