### ISSUE TITLE
Do you plan a modal or fullscreen popup?

### ISSUE THREAD

**Issue by essenov** [Promact/md2#81]
I tried the date and time pickers in my app, everything looks fine except that it the user has to scroll to press OK|Cancel if the date field is in the bottom of the page. Do you plan to implement display modes  that can be switched by a property binding like [displayMode] = "modal|inline|fullscreen"?

**Comment by naspinski** [comment]
This would be great, this also poses a problem if it is inside an overflow:hidden element

**Comment by dharmeshpipariya-zz** [comment]
We have already updated this functionality will release soon.

**Comment by eagor** [comment]
Looks nice, but how do i switch to inline popup mode we had earlier? `md2-datepicker` doesn't seem to have `displayMode` input property, as suggested by @essenov

**Comment by Megamind2301** [comment]
@dharmeshpipariya  how can i implement popup display in mobile for datepicker?

**Comment by dharmeshpipariya-zz** [comment]
@eagor we have refactored datepicker component and it is available on master branch, you can use 'touchUi' property for change display mode, refer our [API Docs](https://github.com/Promact/md2/blob/master/src/lib/datepicker/README.md)
