### ISSUE TITLE
Datepicker format is not enforced on initialization

### ISSUE THREAD

**Issue by naspinski** [Promact/md2#83]
If you feed a _Date_ value through **formControlName** into the <md2-datepicker>, the specified **format** will not be enforced until a date is picked, forcing you to specify also a format.  It owuld be nice if the **format** was enforced at all times.  Thank you, great tools!

Example:
`<md2-datepicker type="date" formControlName="dateVar" format="YYYY-MM-DD"></md2-datepicker>`

this will start out displaying DD/MM/YYYY

But I simply change to this (notice same value):
`<md2-datepicker type="date" formControlName="dateVar" value="{{attributeGrouping.controls['dateVar'].value}}" format="YYYY-MM-DD"></md2-datepicker>`

this will initially display YYYY-MM-DD

This isn't a huge deal, but then when I do this I run into [strange December 31 behavior](https://github.com/Promact/md2/issues/84)

**Comment by maniator** [comment]
Same issue as https://github.com/Promact/md2/issues/69 no?
