### ISSUE TITLE
How to change any control color?

### ISSUE THREAD

**Issue by jmpmscorp** [Promact/md2#88]
Hello guys and thank you for your work.

Could anyone help me? I'm becoming crazy trying to change default color of datepicker. I have been reading #74 but I didn't get success.

I have installed md2 through npm. I have changed default blue everywhere in 'datepicker.css'. I have changed $primary in 'datepicker.scss' but nothing happends, still default blue. I have added an overwrite class in my scss parent component (.md2-datepicker-header{ background: #00bfa5 }), still default blue. I have added the same class in my main style.scss but, again, nothing change.

I hope someone could help and guide me on how to change default color.

Regards.

**Comment by kpolkowski** [comment]
Hi All,

Same problem here (with other controls as well).
I tried following in my styles.scss:

1. Setting the theme:
`@import '~md2/core/theming/prebuilt/pink-bluegrey.scss';`

2. Importing datepicker.scss with variables override:
`$primary: #f44336 !default;
$warn: #f44336 !default;
@import '~md2/datepicker/datepicker.scss';`

All of the above gets overriden somehow by default colors in each md2 control.

However, the second approach generates two style tags in html.
If I delete overriding style tag in Dev Tools, new `$primary` color gets applied.
![image](https://cloud.githubusercontent.com/assets/950382/23233261/9d772bf8-f94e-11e6-91cd-bb713f6a1523.png)


Am I doing something wrong?

**Comment by dharmeshpipariya-zz** [comment]
For theming you can use [SCSS](https://github.com/Promact/md2/blob/master/src/lib/datepicker/datepicker.scss) of it with important property so it will work

**Comment by AndreasStahlHicknHack** [comment]
@dharmeshpipariya Could you please give a short example of how this is supposed to work? I'm running into the same problems as @kpolkowski

This is my current work-around to the problem: I'm not importing the scss file at all, but simply override all classes and elements at the bottom of my app's main scss, based on their usage in the page, which is incredibly fragile and ugly.

```
@include angular-material-theme($my-app-theme);

$primary: map-get($my-app-theme, primary);

.md2-datepicker-header {
    background: mat-color($primary) !important;
}

.md2-button, .md2-calendar-year.selected, md2-datepicker:focus:not(.md2-datepicker-disabled) .md2-datepicker-arrow {
    color: mat-color($primary) !important;
}

md2-datepicker:focus:not(.md2-datepicker-disabled) .md2-datepicker-input {
    color: mat-color($primary) !important;
    border-color: mat-color($primary) !important;
}

.md2-calendar-day.selected {
    background: mat-color($primary) !important;
}

.md2-clock-center, .md2-clock-hand, .md2-clock-hand::before, .md2-clock-hour.active, .md2-clock-minute.active {
    background: mat-color($primary) !important;
}
```

**Comment by geelus** [comment]
@dharmeshpipariya thank you for your workaround. it's working perfectly for me

**Comment by efriandika** [comment]
How to do this @geelus  ? please show me the example.. :(

**Comment by geelus** [comment]
I've copied and pasted it in my them.scss file that I use to theme material design.

**Comment by tw3** [comment]
I have resorted to rules like this in my own scss files

    $my-primary-color: #00ac8b;
    /deep/ .md2-calendar-day {
      &.selected {
        background: $my-primary-color;
        &:hover {
          background: $my-primary-color;
        }
      }
    }

Please tell me if there's a better way to do this by overriding the !default value of the $primary variable within md2, I can't figure it out!
