### ISSUE TITLE
Which version should be considered for Angular 2.1.0 

### ISSUE THREAD

**Issue by AngularTx** [Promact/md2#89]
Which version of md2 should i install for Angular 2.1.0 . Basically the below features I would like to use it . 

1. Dropdown - 
2. Autocomplete - 
3. Select with drop down -

**Comment by AngularTx** [comment]
We are developing the application on IE 11  browser. Are there any known issues with IE?

**Comment by dharmeshpipariya-zz** [comment]
@AngularTx Md2@0.0.10 is compatible with Angular@2.1.0 but we recommend to use Md2@latest(0.0.16), there are few known IE issues we will fix it.
