### ISSUE TITLE
DatePicker - Issue in Karma

### ISSUE THREAD

**Issue by sonthosh** [Promact/md2#93]
The DatePicker is not rendering / behaving as expected in karma.

Please see the screenshot below.
![image](https://cloud.githubusercontent.com/assets/12847649/23138543/0e6b3172-f776-11e6-8b12-8e1f4120fa46.png)

**Comment by ahirhasmukh** [comment]
I am also facing above issue.  Issue occurred when we are using 2 or more date-picker using in one page or one dialog

![desktop](https://cloud.githubusercontent.com/assets/8941195/23160748/a25c097e-f84d-11e6-91e3-fa82da5c8ae7.png)

**Comment by aminsmartsense** [comment]
Hello,

There is a date format issue. Your date format set to IST. because in latest version date format is changed. So your format set in Wed Mar 06 21:00:00 IST 2014.

Thanks

**Comment by ahirhasmukh** [comment]
@dharmeshpipariya Please help us

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.17,
comment here if you have an issue
