### ISSUE TITLE
Datepicker: scroll to selected Year fails

### ISSUE THREAD

**Issue by eagor** [Promact/md2#95]
When opening year selection menu, it fails at https://github.com/Promact/md2/blob/master/src/lib/datepicker/datepicker.ts#L531 with `TypeError: Cannot read property 'offsetTop' of null`, and the menu shows from the beginning: 1900 year.

**Comment by jefersonestevo** [comment]
I think this is the same issue as #99. 

I've sent a pull request to correct this problem: #101
