### ISSUE TITLE
Sorting freeze issue with DataTable

### ISSUE THREAD

**Issue by mtinnes** [Promact/md2#98]
After updating to 0.0.15 my app will lock up (browser freezes) when calling setSort() on Md2DataTable. Previous versions worked fine. I am accessing the table via ViewChild `@ViewChild(Md2DataTable) table: Md2DataTable;` and calling the setSort() method like so `this.table.setSort('uploadedOn', 'desc');`. Is it acceptable to call these methods manually?

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.17,
comment here if you have an issue
